### ISSUE TITLE
Ny property for System: Arkiveringskrav

### ISSUE THREAD

**Issue by mariushart** [JosefAssad/SeMaWi#102]
Det er vigtigt at vide om et system indeholder information som gør det arkiveringspligtigt.
Forslag: boolean Arkiveringkrav

**Comment by JosefAssad** [comment]
Hvad er forskellen mellem bevaringspligt og arkiveringspligt?

**Comment by mariushart** [comment]
Ingen, men jeg kan ikke se Bevaringspligt i properties O_o

**Comment by JosefAssad** [comment]
Ah good. Det er fordi bevaringspligt er et property på et KLE Emne, ikke i et System. Så vi skal rette i Template:System således at den læser Property:Emne_Bevaring fra tilknyttet KLE emne og viser det. :)

Se lige #70 ; dækker den samme behov?

**Comment by mariushart** [comment]
Ja det dækker fint, sorry missede det issue
