### ISSUE TITLE
Opsigelse på kontrakt

### ISSUE THREAD

**Issue by mariushart** [JosefAssad/SeMaWi#112]
Releateret til #93 
Opsigelse på kontrakter kan opgives som
1. Datoformat (nuværende implementering)
2. Relativt tekstformat fx. med 3 mdrs varsel

MVP er at begge felter er mulige
De luxe er at ny property 'opsigelsesalert' genereres ud fra variabel: opsigelsesvarsel - udløb af kontrakt og således kan man danne rapporter for kommende handlerum ifht systemafskaffelser, handlerummet defineres således af opsigelsesvarsel + buffer til adminsitrativt bøvl og beslutningsproces..

Der er to scenarier
1. man overvåger kontrakter for ikke at gå glip at udløbstreshold (kræver ad 1)
2. man ønsker at ophæve en kontrakt og opsøger viden om hvorledes (kræver ad 2)

**Comment by mariushart** [comment]
Det skal i øvrigt overvejes, om prisregulering på lignende vis kan have datoafhængighed, fx ved mulighed for genforhandling

**Comment by JosefAssad** [comment]
Ah cool, meget interessant. Lad os snakke lidt inden vi finder den rette milestone. Mmen lige inden vil jeg gerne splitte denne i to issues: 1 til udvidet format for opsigelsesvarsel, og en til opsigelsesvarsel.

Giver det mening?

**Comment by mariushart** [comment]
Giver fint mening med 
1 udvidet format for opsigelse
2 opsigelsesvarsel

**Comment by JosefAssad** [comment]
Splittet ud i #113 og #114
