### ISSUE TITLE
Dataansvar for geodata overskrives 

### ISSUE THREAD

**Issue by baffioso** [JosefAssad/SeMaWi#116]
Virker til at brugeren angivet i dataansvar overskrives om natten.

**Comment by JosefAssad** [comment]
Efter en snak med @baffioso på [IRC](http://webchat.freenode.net/?channels=semawi) har vi følgende løsningsdesign:

1. Tilføj ansvarlig på KLE emner (Template og Form)
2. Fjern Dataansvarlig fra Geodata (For og Template)
3. Ret i Template:Geodata så den henter dataansvarlig fra pågældende KLE emneside.

**Comment by JosefAssad** [comment]
Implementeret.

Der er på KLE emner tilføjet et nyt delt dataansvarlig som man skal udfylde.

Har man udfyldt dataansvarlig på et KLE emne, og er det KLE emne i "extra" feltet som vi hender fra GC2 så vises automatisk den dataansvarlige på en Geodata side. På den måde overskrives dataansvar ikke.

@baffioso du må gerne teste.

**Comment by baffioso** [comment]
Vi tester

**Comment by baffioso** [comment]
Ser godt ud. Vi skal bare lige have rettet brugersiden til:
![image](https://cloud.githubusercontent.com/assets/7534153/13423961/51d59556-df9e-11e5-8035-16c6cefefae7.png)

**Comment by JosefAssad** [comment]
Ah det er rigtigt. Godt spottet!

Skulle virke nu, vi bruger [#set parserfunktionen](https://www.semantic-mediawiki.org/wiki/Help:Setting_values) til at tilføje property'et i baggrunden.

**Comment by baffioso** [comment]
Benny er ansvarlig for:
http://semawi.notanumber.dk/index.php/Geodata_Beskyttet_naturtype

Men når jeg klikker på Benny, får jeg stadig ikke listet tabeller:
http://semawi.notanumber.dk/index.php/Bruger:Bwj

**Comment by JosefAssad** [comment]
Det er derfor vi glæder os til MediaWiki 1.26.2 som kommer i SeMaWi 2016_01! Den har forbedret MW's job queue funktionalitet en hel del.

Der manglede at jeg kørte php maintenance/runJobs.php på serveren for at refreshe alle skabelonsider.

**Comment by baffioso** [comment]
Det spiller

**Comment by baffioso** [comment]
Kan se at den ikke lister alle tabellerne under Benny. Denne
http://semawi.notanumber.dk/index.php/Geodata_beskyttet_natur_(Bufferzoner) har samme KLE som http://semawi.notanumber.dk/index.php/Geodata_Beskyttet_naturtype, men fremgår ikke under http://semawi.notanumber.dk/index.php/Bruger:Bwj

**Comment by JosefAssad** [comment]
Job queue igen. :) Hvis der er en side du ved har opdateret info men det ikke dukker op, så er det fordi MW har smidt det på job queue. Så kommer det af sig selv senere, når jobbbet kører hvilket sker når der trigges kald til visning af andre sider (ja, det er den form for job control vi skal væk fra med den nyere MW).

Der er dog mulighed for at force et refresh i vores nuværende MW version:

![refresh](https://cloud.githubusercontent.com/assets/1040956/13426201/4fbb1d00-dfac-11e5-8314-3b63eb180ba9.png)

Og ja det er fjollet, men det er den lille "antifeature" jeg beskrev en gang som er i denne her nu ældre MMW version, hvor tingene ikke altid refreshes med det samme hvis man kalder en side og søger på noget der ligger under den. Der er `#set:` kaldet i `Skabelon:Geodata` et godt eksempel.

**Comment by baffioso** [comment]
Achso. Jeg lukker igen

**Comment by baffioso** [comment]
Geodataejerskab opdateres ikke på brugernes profiler, selvom de og data har fået tildelt KLE.

http://semawi.notanumber.dk/index.php/Bruger:Bwj 
er koblet til
http://semawi.notanumber.dk/index.php/Emne_01.05.08 
som er koblet til
http://semawi.notanumber.dk/index.php/Geodata_Beskyttet_naturtype

**Comment by JosefAssad** [comment]
Hm. Yeah, fixede det igen ved at køre maintenance/rebuildall.php, jeg tror det er samme problemstilling som jeg har nævnt før med properties som afhænger af andre properties.

Jeg forestiller mig det er fixed i SMW 2.4 som vi opgraderer til med MW 1.27, men jeg vil gerne finde en midlertidig løsning. I aften installerer jeg udvidelsen [SemanticDummyEditor](https://www.mediawiki.org/wiki/Extension:SemanticDummyEditor) da det er muligt den afhjælper fejlen.

**Comment by baffioso** [comment]
Super

**Comment by JosefAssad** [comment]
Kort status: SemanticDummyEditor er installeret og `LocalSettings.php` har følgende config:

````
require_once "$IP/extensions/SemanticDummyEditor/SemanticDummyEditor.php";
$wgSDERelations = array("Geodata extra", "Emne Ansvarlig");
````

Efter en del test har jeg en teori om, at denne fejl kun ååvirker geodata, og kun når vores batch import overskriver sider fra GC2 kl 5 om morgenen. For eksempel hvis vi manuelt sætter et emne til en bruger dukker taggede geodata tabeller op med det samme, men ikke når scriptet kører. Det er nok fordi scriptet sletter sider og genopretter dem i stedet for at redigere i de eksisterende (det kan være når @baffioso har øvet sig mere i python at vi kigger på at tilrette import scriptet lidt så det redigerer i stedet for at slette og oprette).

Så, det der skal ske nu er at vi venter til næste GC2 import og ser om KLE properties bevares vha SemanticDummyEditor.

Hvis ikke er der en anden løsning som jeg indtil videre har været glad for at undgå, og det er at køre et cronjob umiddelbart efter import som kalder `maintenance/rebuildall.php` hvilket opdaterer det hele og får Geodata tabeller til at dukke op under brugersider.

Den implementerer jeg i morgen hvis SemanticDummyEditor ikke gør hvad vi forventer. Og så har jeg en fornemmelse at den nye MW/SMW som arbejdes på i øjeblikket har forbedret property propagation, det må vi teste senere når dev branchen af seMaWi er klar.

**Comment by baffioso** [comment]
Det lyder godt og håber også en opgradering kan få det til at spille uden for mange ekstra jobs.

**Comment by JosefAssad** [comment]
Alright no luck med Semantic dummy Editor, så der er på produktionsserveren nu implementeret et nyt cronjob som kører rebuildall.php en time efter import af geodata tabeller, dvs. 0600 om morgenen.

Det har større chance for at løse problemet, men er en mindre elegant løsning. Jeg kigger i morgen på server og datastatus efter jobbet er kørt og melder tilbage her.

**Comment by JosefAssad** [comment]
Ser ud til at fungere med cronjobbet. Jeg lader denne issue stå åben foreløbig og double checker om et par uger.

**Comment by baffioso** [comment]
Ser ud til det stadig spiller - Fedt Josef.
