### ISSUE TITLE
Datamodel for Servere

### ISSUE THREAD

**Issue by baffioso** [JosefAssad/SeMaWi#121]
Vi vil gerne have styr på vores servere og hvilke systemer de har installeret
Til en start ville vi oprette Navn og Systemer:
```
Property:ServerNavn
Property:ServerSystemer
```

**Comment by JosefAssad** [comment]
[Simularch](https://github.com/JosefAssad/Simularch) har et bud på sådan en datamodel. Se her:

![structure](https://cloud.githubusercontent.com/assets/1040956/13285409/bcf42274-dafa-11e5-802c-13dd9e290437.png)

Tanker?

**Comment by JosefAssad** [comment]
@baffioso har lavet et godt bud på datamodel til servere. Jeg synes vi skal tage udgangspunkt i den og arbejde videre derfra. I den anledning lukker jeg denne issue og henviser til #141
