### ISSUE TITLE
Dato håndtering

### ISSUE THREAD

**Issue by mariushart** [JosefAssad/SeMaWi#128]
Indtastning af dato må gerne gøres enklere end DD nyt indtastningsfelt Måneddropdown og YYY indtastning.
Kunne Datepicker anvendes i stedet?

https://www.mediawiki.org/wiki/Extension:Semantic_Forms/Input_type_datepicker

**Comment by JosefAssad** [comment]
Yes jeg mener det drillede med DatePicker da jeg implementerede form:ItKontrakt men husker ikke hvorfor.

Du må gerne prøve at ændre til datepicker og sige til hvis det virker. Og også gerne checke i SeMaWi's docker om datepicker også fungerer fint der. :)

**Comment by JosefAssad** [comment]
Faktisk så fungere datepicker fint på BALKs SeMaWi (check fx. `Form:System`) så det ville være rigtig godt hvis du testede på `Form:ItKontrakt`.

**Comment by mariushart** [comment]
Det fungerer rigtigt godt - er også vild med amerikansk notation for dato.. ahhh

**Comment by JosefAssad** [comment]
Er der andre stedet hvor vi kører uden datepicker eller var den form det eneste tilfælde?

Og angående Amerikanske dato'er: hvor ser du det? Jeg for dag/måned/år her i ItKontrakt sider...

**Comment by mariushart** [comment]
Jeg tror at det er den eneste uden Datapicker.

Ahhhh.. i Datepicker får jeg DD MM YYYY, men i output får jeg YYYY MM DD, min user har EN-us som language preference, så måske er den smart?

**Comment by JosefAssad** [comment]
Ah yes det er rigtigt. Er det meget brugerfjendsk at dato'en står på den måde? Det er nemlig meget entydigt.

Det kan laves om ved at give datepicker kaldet i form'en en parameter a la `date format=dd.mm.yy`.

**Comment by mariushart** [comment]
Nej, det er fint - jeg synes det er en feature :)
