### ISSUE TITLE
Datamodel for data

### ISSUE THREAD

**Issue by ballerupgis** [JosefAssad/SeMaWi#13]
Vi har nu er rå skitse der omhandler de systemer vi forvalter, det er et naturligt næste skridt at inkludere hvilke data systemerne håndterer. Der er et stort behov for overblik og hjælp vedr. fremsøgning og anvendelse af data.

**Comment by JosefAssad** [comment]
Syddjurs overvejer et pilotprojekt. som del af scopet skal datamodellen udvides så den omfatter relationer mellem systemer i form af integrationer. Det kan være vi kan arbejde med "integration" konceptet så det dækker jeres behov?

Det er en mulighed. En anden simplere mulighed er en ny "class" som hedder noget i retningen af "DataKilde".

Kan i komme med et kort eksempel på sådan et databehov? Er det f eks når man henter KMS data?

**Comment by ballerupgis** [comment]
Det kan sagtens være, at vi skal modellere skridt i retningen af en egentlig databeskrivelse "integration" kunne være et begreb. Jeg tænker "data" som noget et "system" indeholder, opbevarer, ændrer osv. Data og System understøtter bestemte arbejdsgange i organisationen. Det vi gerne vil kunne svare på er, hvor [system] finder jeg hvilke [data], og hvad [metadata] gælder for data. Det kunne være social- og sundhedsdata, spildevandsdata mm.

**Comment by JosefAssad** [comment]
Aha ok. Ja, det giver god mening, og det er ikke dækket af "Integration" klasser.

Har i et datataksonomi? Det vil være det mest elegante at implementere.

Hvis ikke så kan det være der skal implementeres noget minimalt til at starte med så vi kan føle os inkkrementalt frem til en mere sofistikeret datastruktur.

**Comment by ballerupgis** [comment]
Vi har datamodeller for nogle datasæt, og arbejder på metadata via KLE-tagging af data - så måske en minimalløsningstaxonomi med mulighed for uddybende beskrivelser?

**Comment by JosefAssad** [comment]
Ideelt synes jeg data giver nogle ret specielle muligheder hvis der implementeres tilstrækkelig detaljerede klasser til beskrivelse af data. For eksempel identificering af datatyper (hvad har vi af geografisk data), eller identifikation af autoritative felter og uautoritative felter osv (hvor er postkoder vejnavne beskrevet).

Det ville bare ikke være minimalt. Alternativet er en simplere klasse som peger på et system som har felter som KLE tags (plain text) og så nogle sigende kategoriseringsdropdowns.

Lad os tage en snak om det ved næste møde.

**Comment by ballerupgis** [comment]
Aftale :-)

**Comment by ballerupgis** [comment]
prototypen fungerer, jf. de kommentarer Anders har sendt dig

**Comment by ballerupgis** [comment]
Har været inde og se på geodata og faldt over et datasæt, hvor informationer i form har forskubbet sig. 
http://semawi.notanumber.dk/index.php/Geodata_01_05_bes_naturtyper_5
Det virker til at den lange tekst i "Beskrivelse" har rykket de efterfølgende felter et hak. 
(PS skal dette registreres under et nyt issue?)

**Comment by JosefAssad** [comment]
Ah interessant; kigger på det. Fint bare at skrive det på denne issue!

**Comment by ballerupgis** [comment]
Vi kan også overveje at lave feltet "Bruges i system" i formen, hvor vi linker til systemerne. Jeg ved ikke om dette kan autogereres vha. KLE som nøgle. Kunne forstille mig at det ville lede til fejl og vi nok skal tilknytte systemerne manuelt.
- Anders

**Comment by JosefAssad** [comment]
Ja, det er en rigtig god ide. Også, på brugersiderne skal der listes hvilke tabeller de har dataansvar for; det har jeg ikke implementeret endnu så Lars ikke ender med en lang liste på 714 tabeller. :)

**Comment by ballerupgis** [comment]
Jeg kan leve med det :-) Det ser godt ud, vi har taget et kæmpe skridt fremad........tror vi skal mødes over en kop kaffe og få tegnet/opridset næste fase
* Lars

**Comment by JosefAssad** [comment]
Forskubbede info skulle være fixed nu.

Der er uploadet nyt [commit](https://github.com/JosefAssad/SeMaWi/commit/4d4b9bb8ef86d5f98ba6398fe36d5e624f2cbba8) med konverteringsscriptet, og dokumentationen er opdateret.
