### ISSUE TITLE
Wikihelper

### ISSUE THREAD

**Issue by mariushart** [JosefAssad/SeMaWi#131]
Wikitext-funktion:Masseretfunktionalitet

- Definer funktionalitet (Anders, Marius, Josef)
- Udvikl funktionalitet Find property, ret property (Marius)
- Do. bugtestes (Anders)

@baffioso  @mariushart

**Comment by JosefAssad** [comment]
Moved to https://github.com/JosefAssad/semawihelper/issues/1
