### ISSUE TITLE
property for dokumentationskvalitet

### ISSUE THREAD

**Issue by JosefAssad** [JosefAssad/SeMaWi#136]
Nu hvor vi begynder at se sider med et rigtig flot dokumentationsniveau begynder det at være oplagt at beskrive de forskellige siders dokumentationsniveau eller kvalitet.

En (i min optik) ret vigtig use case er, at danne en rapport som viser hvilke sider mangler at dokumenteres. Sammenlignet for eksempel med et property som flagger hvor vigtig et system er vil vi kunne danne en rapport som viser hvor vi har størst gap mellem dokumentation og "mission criticality" så vi ved hvor dokumentationsindsats skal fokuseres.

Property'erne kan være rimelig generiske (f. eks. Property:DokumentationKvalitet og Property:MissionCriticalRating). På den måde kan de bare tilføjes til Template:System og øvrige templates.

Tanker? @ClockEnd @lenethystrup @baffioso @mariushart

**Comment by mariushart** [comment]
På beta.rammearkitektur.dk anvendes en simpel 1-5 status for kvaliteten af indholdet.

http://beta.rammearkitektur.dk/index.php/Om_Status

**Comment by JosefAssad** [comment]
Den temmplate er rigtig fin, det kan være vi skal stjæle den. Men den er til services, jeg tænker her noget lidt mindre ambitiøst, bare en simpel skala som beskriver hvor grundigt det en side handler om er dokumenteret. F. eks. fra "Crap" til "verdensklasse".

Faktisk kunne vi næsten lave en "metatemplate" fra den template på beta.r.d så alle ratings har samme form, uanset om det er rating på dokumentationskvalitet eller andet som vigtighedsrating og lignende...

**Comment by mariushart** [comment]
God ide med 1-5 status, som jeg husker er en 'penta-centrisk-angivelse' også udbredt til kompetence angivelser e.g. (from the top of my mind) heard of, can work under instruction, can perform independantly, can teach others, expert
