### ISSUE TITLE
eksterne databasekald

### ISSUE THREAD

**Issue by JosefAssad** [JosefAssad/SeMaWi#146]
Jeg sad lige og læste i nogle dokumentationssider i har oprettet. Der bliver dokumenteret en del om opslag i databser vha. SQL; det fik mig til at tænke på en udvidelse jeg har haft i backlog i et stykke tid:

[Extension external data](https://www.mediawiki.org/wiki/Extension:External_Data)

Den kan [kalde SQL databaser](https://www.mediawiki.org/wiki/Extension:External_Data#.23get_db_data_-_retrieve_data_from_a_database). Er det noget i kan finde use cases til?

Cc @baffioso @Neogeografen @ClockEnd

**Comment by ClockEnd** [comment]
Jeg tænker, ja! Vi kommer utvivlsomt til at håndtere andre data end de geo-orienterede, kunne forestille mig wikien kunne bruges til evaluering, exploring og måske download og videre i CKAN..? Har jeg helt misforstået konceptet og/eller den virkelighed vi agerer i?

**Comment by JosefAssad** [comment]
Jeg tror du har forstået konceptet mere eller mindre rigtigt. Et lille fiktivt eksempel.

Hvis du sidder og skriver dokumentation for en geodata tabel om for eksempel lygtepæle. Så kan det være du har lyst til at skrive "tabellen har i øjeblikket 72 lygtepæle". Det der tal vil normalt være hardcoded i siden, og så kører du dil SELECT query ved siden af for at finde det rigtige tal.

Med denne udvidelse kan den værdi hentes on-the-fly fra databasen.

**Comment by baffioso** [comment]
Jeg har nu en brugbar usecase for dette!!!

@JosefAssad  sendte tidligere mail med forslag til at strukturere beskrivelsen af kolonner i en tabel. Her kan man kalde PostgreSQL og få listet alle kolonnetitler i en tabel, som derefter tilføjes Wikien og er klar til at blive beskrevet ([se eksempe på intern serverl](http://10.192.224.40:12345/index.php/Geodata_Anl%C3%A6gsprojekter_(BK)#Databeskrivelse)).  
```
SELECT *
FROM information_schema.columns
WHERE table_schema = 'schema'
  AND table_name   = 'table'
```

Tror snart vi skal til at opdele geodata informationerne på flere faneblade, hvor et af dem kunne være kolonnebesrkivelse (eller noget mere liret).

(Jeg er har kigget lidt på psycopg2 modulet i python hvis der bliver brug for det)

**Comment by JosefAssad** [comment]
Det er en genial use case. Vi har tre delopgaver der:

* Opret forbindelse til GC2 postgresql i LocalSettings.php
* Indlejr database kald i Template:Geodata
* Vis tabel metadata i semantiske properties

Jeg opdaterer github med ExternalData, og installerer det på containeren i løbet af ugen, så kan vi snakke om hvordan vi afprøver konceptet.

**Comment by JosefAssad** [comment]
Cc @mariushart da det simpelthen er en grænseoverskridende cool use case

**Comment by JosefAssad** [comment]
Jeg har installeret ExternalData på containeren så vi kan teste lidt. Vi mangler lidt info inden du kan teste database kald fra wiki'en. I `LocalSettings.php` skal der defineres adgang til en database som ses [her](https://www.mediawiki.org/wiki/Extension:External_Data#Configuration).

Kort fortalt er det vi mangler:

```
$edgDBServer['ID'] = "server URL";
$edgDBServerType['ID'] = "DB type"; 
$edgDBName['ID'] = "DB name";
$edgDBUser['ID'] = "username";
$edgDBPass['ID'] = "password";
```

Har i en test DB vi kan bruge? Når du har de oplysninger kan du bare maile dem. :)

**Comment by baffioso** [comment]
Så er det sendt. Vi kører på en readonly bruger

**Comment by JosefAssad** [comment]
http://10.192.224.40:12345/index.php/Sandkasse (se sidens wikitekst, der kan du se de db kald der er anvendt)

:)
