### ISSUE TITLE
Ny data 

### ISSUE THREAD

**Issue by baffioso** [JosefAssad/SeMaWi#147]
Vi har snakket med de andre centre om at prøve at samle dokumentation for kommunens data i Wikien, hvilket betyder at vi enten (1) udvider datamodellen for den nuværende geodatakategori eller (2) opretter en ny kategori som vi evt. kalder "data".

Har modtaget følgende udkast til datamodel:
![image](https://cloud.githubusercontent.com/assets/7534153/17555233/234a3642-5f0f-11e6-8181-421e4a89650e.png)

Hvad tænker I?

**Comment by baffioso** [comment]
Udsnit af chat om opbygning:
<JosefAssad> Hvad siger du til, at der implementeres en klasse præcis som det diagram der, dog med et ekstra felt
<JosefAssad> det ekstra felt er noget i retningen af "underordnede geodata tabeller"
<JosefAssad> på den måde kan vi bevare eksisterende geodata funktionalitet men relatere det til det mere generelle data
<baffioso> hvor der linkes til gc2-script-sider. Lyder som en god løsning

**Comment by baffioso** [comment]
Så er der implementeret prototype på dev

**Comment by baffioso** [comment]
Registrering af data fører måske til ny udvidelse. Har henvist til systemer der hvor vi angiver kilden, men kan være vi skal oprette ny kategori databaser/registre/datasamling? De vil så have relation til software f.eks. Postgres/MySQL/MSSQL.

TANKER?

**Comment by JosefAssad** [comment]
Løse tanker:

1. helt overordnet er det en rigtig god ide at få mere detalje ind i systemet. Det er væsentlig bedre at sige "LOIS indeholder eksakt datasets A B og C" end "LOIS indeholder borgerdata" (bare eksempel).
2. En potentiel udfordring: nogle datasets henvises til ved et unikt navn (f. eks. CVR). Men et dataset can findes mere end et sted i systgemporteføljen, og de er ikke altid ens. for eksempel kan der være et system som bruger BBR dataset i helhed og et andet som gemmer et subset af BBR, hvordan skal de registeres i datamodellen? Det er data om samme genstand men de egentlige dataset er ikke ens, hverken i indhold eller i use cases.
3. En anden udfordring: hvikle datasets skal datamodellen rumme? For hvert navngivet dataset (CVR, BBR, etc) er der 10 unavngivne datasets. Det betyder ikke nødvendigvis at det kun er de navngivne der er interessant/relevante. for eksempel, GC2 databsasen indeholder geotabeller. Er det et dataset eller er det flere? Det er afhængig af kontekst. for en DBA er det måske et dataset men for en vandforsyningsprofessionel kan der være flere tabeller der betragtes som selvstændige datasets.
4. Hvis et dataset caches skal det registreres? Hvis for eksempel i tager [CPR Broker](https://github.com/OS2CPRbroker) i brug så (svjh) cahces der CPR data i en MySQL database, men andre systemer der slår CPR op i CPR broker kan måske også gemme CPR data. Hvordan vil vi registrere det scenario i wiki'en?
5. Vi kan ikke sige at dataset X ligger på PostgreSQL da PostgreSQL er lidt for abstrakt. I kan have mere end en psql database kørende; hvilken en? Der kommer vi til en nuance jeg selv har modelelret i systemportefølje arbejde tidligere og som vi indnu ike har i SeMaWi: sondring mellem et system og et deployeret instans. Se følgende billede og læg især mærke til klasserne System, SystemVersion, DeployedSystemVersion, InfrastructureFacility, og Server.

![structure](https://cloud.githubusercontent.com/assets/1040956/17661196/f67ea2ec-62dd-11e6-82ae-b8d44bcf37e2.png)

Det betyder at, for at kunne sige at et dataset ligger på et bestemt system så skal vi udvide system datamodellen en del og introducere infrastrukturmodellering. Begge dele er en skidegod ide men er ikke trivielt. Det er noget vi skal overveje. The good news is, en evt. datamodel for infrastruktur er ikke noget der ændrer sig hver 5 minutter så det er meget arbejde i starten men vedligehold kan være nemmere.
6. Lidt food for thought: det kan være vi kan komme langt med en udvidet datamodel for data hvis vi læner os op ad klassisk data warehouse teori. Se følgende diagram som viser forskelle mellem conceptual/logical/physical data model:

![dm](https://cloud.githubusercontent.com/assets/1040956/17661330/cf40a13e-62de-11e6-9a63-e346e8655068.png)

Hvis vores datamodel for data tager udgangspunkt i for eksempel den logiske model så ja det er rigtig meget arbejde i starten når data skal ligges ind, men så har vi et ret præcist billede ad HVAD de forskellige systemer rummer af data.

right back at you, tanker?

**Comment by baffioso** [comment]
Du er kongen af lange svar. Svarer lige lidt ustruktureret tilbage:

Har lige snakket lidt med Lars og vi er kommet frem til at registrere LOIS under Systemer med afhængighed til MSSQL. Det der nok forvirrede mig var skelnen mellem fagsystemer (f.eks. KMD-produktuer) og software-systemer (MySQL m.m.). Det vigtigste er at vi kan finde frem til systemet som indeholder data. Her hjælper MSSQL os ikke, da den type database bruges mange steder i organistion, men det gør LOIS, da den indeholder et afgrænset antal datasæt.

Som du er inde på er det svært at sige hvornår et datasæt skal med, men vi må starte med dem som er centrale for forretningen og kan have interesse på tværs af centrene. I forhold til flere versioner af det samme datasæt tænker jeg at vi håndterer det når/hvis det giver udfordringer.

ifht. sidste del tror jeg vi skal tage den næste gang vi mødes.

**Comment by JosefAssad** [comment]
Alright, det lyder pragmatisk og det kan jeg godt lide.

Jeg har reviewer DataOmData klassen og har foreløbig ingen yderligere kommentarer. Skal jeg flytte den over på PROD?

Når vi har gjort det synes jeg der kun mangler en lille ting, og det er at vise en automatisk genereret oversigt under et System for hvilke datasæt systemet rummer; det ordner jeg når i har sagt go for flytning af klassen til PROD.

**Comment by baffioso** [comment]
Smid det bare på PROD.

**Comment by JosefAssad** [comment]
Done! Når der kommer datasets på som linker til eksisterende systemer kan jeg oprette oversigten jeg nævnte på systemsiderne.

**Comment by baffioso** [comment]
Tak - og tak for at smide den i sidebar
