### ISSUE TITLE
Mobo

### ISSUE THREAD

**Issue by baffioso** [JosefAssad/SeMaWi#149]
Se på https://github.com/Fannon/mobo til datamodellering

**Comment by JosefAssad** [comment]
Faktisk ret sexy. Vi kan allerede køre [diffs](https://en.wikipedia.org/wiki/Diff_utility) på SMW datamodeller ved hjælp af et git filter jeg har skrevet [her](https://github.com/JosefAssad/mw-xml-filter). Men det er sandsynligt at denne json-agtige syntaks egner sig til klarere diffs.

Det eneste jeg har imod det er at det er [node.js](https://kaushalsubedi.com/blog/2014/10/15/node-js-sucks-heres-why/) som jo er en teknologisk krigsforbrydelse men de implementerede funktioner er interessante nok til at jeg bider tungen og henter panodil og prøver det af. Jeg vil bare være sikker på at den ikke indeholder showstoppers inden vi vurderer Mobo mere seriøst.

Godt fundet!

**Comment by JosefAssad** [comment]
Jeg har nu endelig fået kigget på mobo. Jeg synes ideen er rigtig god, men synes ikke vi skal skifte over til den. Det ville ellers være ret nice, fordi json/yaml er en del nemmere at versionsstyre (specielt hvad angår diffs), men.

Dokumentationen er ok, men jeg tror ikke den er på flere områder god nok. Mange af vores standard vaner ser ikke ud til at være fokus i mobo, for eksempel at vi bruger kategorier til at samle sider som udgør datamodel for en ny feature. Det eksempel er noget utrolig essentielt for os; måske hvis man graver rigtig dybt i mobo kan det lade sig gøre 

mobos primære use case er en hvor man helt i starten kører med mobo, og vi har jo en stor og ret moden datamodel som ikke er implementeret i mobo. Så hvis vi gik med mobo ville vi enten igennem en større konverteringsøvelse eller leve med hybrid mellem vanilla SMW og mobo. Begge muligheder er ikke så optimale.

Min mavefornemmelse er, at man ikke sparer så meget tid og kræfter hvis man bruger mobo - selv fra starten. Uden at have kigget dybere i mobo ville min bekymring også være, at jeg tvivler på at der nogensinde kunne være en "korrekt" tovejs oversættelse mellem wikitext og json/yaml. Jeg ved ikke hvor præcis wikitext ligger i [Chomsky hierarkiet](https://en.wikipedia.org/wiki/Chomsky_hierarchy) men wikitext har ingen formel specifikation, og jeg tvivler på om det kan udarbejdes.

Jeg sætter en husker ind i kalendern at kigge igen på mobo om 12 måneder, kunne være der sker noget på den front.
