### ISSUE TITLE
installer udvidelse til redigering af konti

### ISSUE THREAD

**Issue by JosefAssad** [JosefAssad/SeMaWi#152]
Det sker at en bruger skifter mail adresse for eksempel, eller skifter navn (e.g. ved ægteskab).

Brugerinformation kan naturligvis skiftes direkte i databasen men det vil være mere hensigsmæssigt at bruge en udvidelse til dette formål. Jeg tester udvidelsen [EditUser](https://github.com/wikimedia/mediawiki-extensions-EditUser) på dev og tilføjer den i PROD og på github her hvis den er god nok.

**Comment by baffioso** [comment]
+1

**Comment by JosefAssad** [comment]
Lille OBS er kun implementerer i docker versionen.
