### ISSUE TITLE
DNS til wikien

### ISSUE THREAD

**Issue by baffioso** [JosefAssad/SeMaWi#156]
Vi får oprettet en DNS som vi kan bruge internt.

**Comment by baffioso** [comment]
Der er nu oprettet wiki DNS som ligger her:

http://wiki/
eller
http://wiki.balk.dk/

Lige nu kommer vi ind på GC2, så @JosefAssad  skal nok lige ind og omdirigere.

**Comment by JosefAssad** [comment]
Lige for dokumentationens skyld er status her, at vi afventer koordinering med Mapcentia. GC2 bruger port 80 så det er derfor GC2s DNS fungerer. Det ligner at standard practise når man skal have flere containere på en host til at svare på forskellige DNS entries er, at man bruger [nginx proxy](https://github.com/jwilder/nginx-proxy). Det kræver dog, så vidt jeg kan se, genstart af en del containere og (muligvis) tilpasning af containernes run parametre.

Jeg har skrevet til Martin. Indtil den tid så omdirigerer følgende to URL'er alligevel til wiki'en:

http://wiki:12345

og

http://wiki.balk.dk:12345

**Comment by baffioso** [comment]
@JosefAssad Hvad er status med DNS - Mangler du stadig svar fra Martin?

**Comment by JosefAssad** [comment]
Skull fungere nu. Check venligst :)

**Comment by baffioso** [comment]
Har tjekket og ser godt ud
