### ISSUE TITLE
Projekt kategori

### ISSUE THREAD

**Issue by baffioso** [JosefAssad/SeMaWi#160]
@JosefAssad @ClockEnd Vi har gang i flere projekter, som har relation til både data, brugere og systemer og overvejer en projektkategori til overordnet dokumentation og for at samle relationerne. 

Det kunne f.eks. være belysningsprojektet, som indeholder flere dynamiske datasæt, som kunne være godt at få samlet under en hat. 

En simpel datamodel kunne være
- Navn
- Relation til data
- Relation til analyser
- Relation til brugere
- Relation til systemer

Lars er gået i gang med at dokunmenterer noget i den retning her:
http://10.192.224.40:12345/index.php/Bymidtemonitering

Ligeledes er der lavet en beskrivelse af en dataudvælgelse her:
http://10.192.224.40:12345/index.php/LIFE-Science

Ved ikke om sidste kræver endnu en kategori da det ikke som sådan er et projekt, men nærmere en metode.

Tanker?

**Comment by JosefAssad** [comment]
Jeg synes helt klart det er en god ide at oprette en klasse for projekter. I første omgang en tynd klasse med kun de felter du nævner.

Ville KLE være et relevant felt?

Måske også et felt med kort(-ish) beskrivelse, hvis i for eksempel bliver bedt om udtræk af oversigt over projekter.

Og så kunne start- og forventet slutdato måske være relevant?

Jeg synes Lars' dataudvælgelse umiddelbart ikke nødvendigvis er et projekt som sådan. Det falder lidt i mellem system og data. Har jeg forstået rigtigt at det er kode til udtræk af en bestemt type virksomhed fra LOIS databasen? Hvis det er korrekt kunne det være den af LOIS dokumentationen. Hvis behovet for at dokumentere hvordan man trækker datatype X fra system S så kan vi overveje en særskilt klasse.

**Comment by ClockEnd** [comment]
LIFE-Science mener jeg ligger under *Data' ganske vist kun et view af CVR (som vi henter fra LOIS-databasen), mens 'Bymidtemonitering' mere er et projekt, en metode der trækker på flere datasæt. Jdeg tror det er et spørgsmål om, hvor vi lægger databeskrivelser af ikke-geografiske data - som ikke ligger på GC2?

**Comment by JosefAssad** [comment]
Jeg mener det er fint at LIFE-Science ligger under data, selv om der er felter til geodata er de ikke obligatoriske. Hvis modellen for Data udvides med felter til ikke-grografisk data så kan vi bare beuge faneblade i Form'en, så kan man vælge hvilke typer metadata man vil knytte til siden.

Hvordan lyder det?

**Comment by ClockEnd** [comment]
Det lyder rigtigt - og så oprette Kategori:Projekter for sig

**Comment by baffioso** [comment]
Projekt kategorien er oprettet men har brug for en omgang, da det vist blot at en kopi af den oprindelige datakategori. Som beskrevet i tidligere kunne en simpel datamodel være:

- Navn
- Beskrivelse
- Relation til data
- Relation til brugere
- Relation til systemer

**Comment by JosefAssad** [comment]
Det er delvis implementeret:

*Navn: findes
* Beskrivelse: findes
*Relation til data: findes ikke
* Relation til brugere: findes ikke
* Relation til systemer: findes, men skal laves om til at understøtte mere end 1
*KLE-numre: findes

Der findes nogle sider under projektkategoriet i forvejen som bare kan blive der foreløbigt. Et eksempel er siden LoRaWAN. Det er en "plain" wikiside så den passer ikke rigtig ind som sådan i projekter klassen, men siden er vidensmæssigt en enorm flot showcase for blandet indhold i wiki'en, så jeg stemmer for at den bliver selv om den ikke umiddelbart følger klassens datamodel.

Hvis det lyder ok så implementerer jeg bare.

**Comment by baffioso** [comment]
Der nu lavet første udkast til disse rettelser som kan ses [her](http://wiki/index.php/Kategori:Projekter).

**Comment by JosefAssad** [comment]
Det ser super ud! Jeg har reviewet og udført følgende ændringer:

1. Gjort beskrivelsesfeltet lidt længere
2. Tilføjet datarelation til projektkategoriet
3. Sider i Data kategoriet viser nu de projekter de anvendes af (backlinks)
4. Sider i System kategoriet viser nu de projekter de anvendes af (backlinks)
5. Brugersider lister nu de projekter brugeren er dataansvarlig på (backlinks)

Så burde vi datamodelmæssigt være mere eller mindre i mål!

**Comment by JosefAssad** [comment]
+1 for Close herfra. Hvad siger i?

**Comment by baffioso** [comment]
Jeps, har lige tilføjet geodata.
