### ISSUE TITLE
MB-limit upload

### ISSUE THREAD

**Issue by ClockEnd** [JosefAssad/SeMaWi#161]
mange af de pdf-er jeg vil uploade er større end 2MB - kan grenzen hæves til noget mere?

**Comment by JosefAssad** [comment]
Yep! Det kræver lige genstart af containeren, potentielt at jeg rebuilder image så php.ini splittes ud i en ekstern volume. Noget imod at vente til weekenden da det kan tage lidt tid, og containeren vil være midlertidig utilgængelig?

**Comment by ClockEnd** [comment]
Det er fint, ingen hastværk med det - kan bare se at vi i fremtiden rammer ind i store pdf'er - DKs digitaliseringsfavoritformat nr.2

**Comment by JosefAssad** [comment]
Afhænger af #163
