### ISSUE TITLE
oversigt over data i systemer

### ISSUE THREAD

**Issue by JosefAssad** [JosefAssad/SeMaWi#166]
Nu hvor der er implementeret en datamodel for data som peger på System sider vil det være oplagt at tilføje en oversigt på Skabelon:System som viser hvilke data sider systemet indeholder.

@baffioso har du lyst til at implementere?

**Comment by mariushart** [comment]
Ach so.
System -> Data -> Integrationer -> (Information)Data flows -> Forretningsprocesser?

**Comment by ClockEnd** [comment]
Ser fornuftigt ud

**Comment by JosefAssad** [comment]
@mariushart yep, vi har de første to lige nu. Integrationer er ikke så svær (det er jo i dfen mest minimale udgave ikke er mere end to felter, client og server, men så kan der komme masser af lækre metadata elementer som protokol osv. )

Hvis vi så opmærker integrationen med hvilke data integrationen transmitterer, fra  det data et system har så ja, der der tror jeg vi er begyndt at mappe informationsflow.

**Comment by JosefAssad** [comment]
Vi har nu denne relation.

I kategoriet data angiver vi autoritative systemer. På systemsiden viser vi nu (har lige implementeret) de datasæt systemet er autoritativt for.
