### ISSUE TITLE
Billeder virker ikke på interne Wiki

### ISSUE THREAD

**Issue by Neogeografen** [JosefAssad/SeMaWi#168]
Billeder vises ikke på Wiki pt.
fx http://10.192.224.40:12345/index.php/QGIS

**Comment by JosefAssad** [comment]
Ah yes, fik ikke flyttet billeder over. Kører lige rebuildall.php

Det var pga. de her småfejl vi skulle teste inden. :)

**Comment by JosefAssad** [comment]
Check venligst. :)

**Comment by Neogeografen** [comment]
Så er billederne tilbage - tak for fikseriet
