### ISSUE TITLE
Kan ikke uploade billeder pt

### ISSUE THREAD

**Issue by Neogeografen** [JosefAssad/SeMaWi#169]
Når jeg oploader et billede på http://10.192.224.40:12345/ - så sker der godt nok et pre-view af billedet men når jeg så klikker "Læg en fil op" knappen. Så får jeg denne fejlmeddelse

"Exception encountered, of type "LocalFileLockError"

Billeder  er ikke åbne i nogen billedeeditor, så det kan ikke være grunden.

**Comment by JosefAssad** [comment]
Tror det er samme som #159 . Kan du teste nu?

**Comment by Neogeografen** [comment]
Så virker det igen! - jeg lukker tråden - tak for at fikse.
