### ISSUE TITLE
Forklaring af felter i form (evt. ved mouseover)

### ISSUE THREAD

**Issue by ballerupgis** [JosefAssad/SeMaWi#17]
Det ville hjælpe ved oprettelsen af f.eks. et nyt system, hvis felterne som udfyldes blev forklaret lidt bedre. Det kunne f.eks. være uddybning af Leverandør/Driftsleverandør eller Ejer/Administrator, som jeg til tider har svært ved at kende forskellen på.

**Comment by JosefAssad** [comment]
Det er en rigtig god ide. Det kan gøres ved implementering af [tooltips](https://semantic-mediawiki.org/wiki/Help:Adding_tooltips) for felterne.

Når det gøres for `Form:System` så kan vi lige så godt gøre det for de to øvrige forms, `Form:Leverandør` og `Form:Bruger`.

Det kan klares på højst 4 timer. Hvordan lyder det?

**Comment by ballerupgis** [comment]
Det lyder som en god ide, lad os køre videre med det
