### ISSUE TITLE
Billeder fra 6 og 7 oktober ikke uploadet - døde

### ISSUE THREAD

**Issue by Neogeografen** [JosefAssad/SeMaWi#170]
Det ser ud til at billeder jeg har uploadet 6/7 oktober 2016 ikke er live mere.

Se billederne tilknyttet denne side her - er kun blanke
http://10.192.224.40:12345/index.php/Lagerhal_materialeg%C3%A5rden

**Comment by JosefAssad** [comment]
Den her er mere eller mindre det samme som #168 . Da jeg flyttede billeder fra backup til produktion var der er kort vindue hvor allerede ikke-uploadede billeder ikke var med i backup'et.

Jeg har fixet det nu, sig til hvis du finder andre image links der lige skal have et spark i bagdelen fra mediawiki så de vises. :)

**Comment by JosefAssad** [comment]
Regner med det virker nu :)
