### ISSUE TITLE
Speciel:ChangeEmail virker vist ikke

### ISSUE THREAD

**Issue by Neogeografen** [JosefAssad/SeMaWi#172]
Jeg prøver at skifte e-mail fra srj1@balk.dk til sjo1@balk.dk i min brugerkonto

Følger guiden og kommer til siden

"En e-mailbekræftelse er sendt til den angivne e-mailadresse
Før flere e-mails bliver sendt til kontoen, skal du følge instruktionerne i e-mailen, for at bekræfte at kontoen rent faktisk er din."

Jeg har ikke modtaget nogen mail efter 30 min. på den nye konto som jeg skal verificere med et link - Jeg har tjekket om mailen skulle være gået i MS Outlook spam-bakke og det er den ikke.

/Søren

**Comment by JosefAssad** [comment]
Yeah, kender til den sag. :) Mediawiki bruger en ekstern mail server til at sende. Da vi var på Linode var det nemt nok, men på den interne mailserver har jeg været lidt tilbageholdende med at installere en hel postfix deploy på serveren. Det er ret komplekst og jeg ville vente og se om mail funktionen blev brugt.

Jeg vil gerne undgå at vi i første omgang bruger en standalone lokal MTA i stedet for at gå igennem en større Exchange integrationsøvelse, så kigger lige på den mulighed.

**Comment by JosefAssad** [comment]
Alright, tror jeg har en ide, men kigger på det om aftenen når i ikke bruger systemet og efter jeg har taget backup. :)

**Comment by JosefAssad** [comment]
Lige lidt followup, fungerer det nu?

**Comment by JosefAssad** [comment]
Jeg regner med at det virker nu, har ikke hørt der skulle være problemer. :)
