### ISSUE TITLE
Analyser

### ISSUE THREAD

**Issue by baffioso** [JosefAssad/SeMaWi#175]
Vi laver ofte analyser for andre centre med personfølsomme data . Det bliver større krav til dokumentationen til sådanne analyser i fremtiden, så vi overvejer at oprette en analyse kategori.

Props:
Modtager af analyse

**Comment by ClockEnd** [comment]
Den er købt

**Comment by JosefAssad** [comment]
Yep, giver god mening at datamodellere noget der i stigende grad udskiller sig som arbejdsemne.

Kan i komme her i denne github issue med nogle eksempler? Dels for sokumentationens skyld, dels så vi kan pingponge på datamodel design.

**Comment by JosefAssad** [comment]
Jeg kan se at i bruger http://10.192.224.40:12345/index.php/Analyser til dette. Skal der laves noget ud over?

**Comment by baffioso** [comment]
Tænker at der skal laves en template så vi får mulighed for at filtrere lidt i analyserne

**Comment by JosefAssad** [comment]
Yep, så mangler vi at definere hvad for nogle felter der skal være.

analyseansvarlig og kunde, for eksempel?

**Comment by baffioso** [comment]
Henvisning til hvilke data der er brugt. Personfølsom boolean

**Comment by JosefAssad** [comment]
[Roger](http://10.192.224.40:12345/index.php/Kategori:Analyser).
