### ISSUE TITLE
flyt db oprettelse ud af image build

### ISSUE THREAD

**Issue by JosefAssad** [JosefAssad/SeMaWi#177]
Det giver problemer når der kører N>1 instans op imod samme MySQL server.

**Comment by JosefAssad** [comment]
Ah... den her er uforventet kompleks. Det er problematisk at db oprettes under image build i tilfældet af flere insanser på samme docker host.

Men det mest nærliggende alternativ er ikke elegant i min optik: den er, at jeg installerer MW lokalt og ligger de forinstallerede filer plus db dump i docker folderen. Det vil løse problemet, men den store ulempe er, at det ødelægger vores "build reproducability".

Den her skal tænkes på en del mere, skifter milestone til 2017.

**Comment by danchr** [comment]
Jeg ville lave et script der gjorde følgende:
1. Check om databasen er oprettet.
2. Hvis ikke, opret og initialiser den.
3. Start webserveren.

Der er i hvert fald den tilgang jeg på regner med at følge på sigt med LoRa.

**Comment by JosefAssad** [comment]
Jo har wrappet det i et bash script. :) Det føles bare lidt "udockerish" at man egentlig ender med at konfigurere applikationen i bash, men i det mindste virker det.
