### ISSUE TITLE
Brugervenlig teksteditor 

### ISSUE THREAD

**Issue by baffioso** [JosefAssad/SeMaWi#178]
Jeg kom lige ind på mediawiki og så deres teksteditor:

https://www.mediawiki.org/wiki/Extension:External_Data?action=edit#.23get_db_data_-_retrieve_data_from_a_database

Den er ret brugervenlig. Er det et plugin?

**Comment by JosefAssad** [comment]
Hm, hvilken text editor MW bruger er sat op i brugerens indstillinger, der har jeg den almindelige valgt, ser sådan her ud:

![editor](https://cloud.githubusercontent.com/assets/1040956/20244779/cc4fcf1c-a98e-11e6-800f-374b93cbd08a.png)

Ser det anderledes ud fra din side? Evt. se #100

**Comment by baffioso** [comment]
Kopi af #100
