### ISSUE TITLE
Fejl i nybygget dockerinstans

### ISSUE THREAD

**Issue by danchr** [JosefAssad/SeMaWi#179]
```javascript
TypeError: undefined is not a constructor (evaluating 'new EventEmitter()')
```

Jeg har netop bygget en instans af SeMaWi med Docker, og jeg får ovenstående fejl på alle sider. Så vidt jeg kan se er der indhold i wikien — men fejlen forhindrer det i at blive vist. Jeg brugte følgende software:

* Ubuntu 14.04LTS
* Docker 1.12.3
* mariadb:latest fra Docker

Er der nogen af jer der har nogle idéer til hvad der går galt — eller eventuelt hvad jeg gør forkert?

Tak!

**Comment by mariushart** [comment]
Hej Dan,

der ligger nogle anvisninger til installation i de første 4 linier af docker/Dockerfile med nogle prædefinerede Docker anvisninger har du brugt disse?

> docker build --build-arg DBHOST=172.17.0.1 --build-arg DBUSER=wiki --build-arg DBPASS=wiki -t semawi -f docker/Dockerfile .

vh
marius

**Comment by danchr** [comment]
Ja, og efter at have kigget lidt på `docker/Dockerfile` justerede jeg min opsætning så jeg kunne køre:

    $ sudo docker run --name semawi-mariadb -e MYSQL_RANDOM_ROOT_PASSWORD=yes -e MYSQL_DATABASE=wiki -e MYSQL_USER=wiki -e MYSQL_PASSWORD=wiki -p 3306:3306 -d mariadb:latest
    $ sudo docker build -t semawi -f docker/Dockerfile .
    $ sudo docker run -d --name semawi-container -h semawi-container -p 8000:80 semawi

**Comment by JosefAssad** [comment]
@danchr det er lidt usædvanligt at SeMaWi kræver en DB under `build` fasen, jeg har en opgave med at finde på en måde at undgå det. Jeg regner med, at det var der fejlen opstod, yes?

**Comment by danchr** [comment]
Nej, desværre. Jeg var vist lidt for kortfattet: Det lykkedes mig at få instansen op at køre så jeg kunne se SeMaWi — og det var her jeg så fejlen i JavaScript-koden. Det var sådan set også derfor jeg rapporterede den; jeg har lidt svært ved at gennemskue hvordan noget jeg gjorde eller ikke gjorde skulle give en fejl på det niveau…

Jeg er 90% sikker på at selve MediaWiki virker som den skal; jeg kan importere data med et script, og se koden hvis jeg prøver at redigere siden. Men samtlige sider giver ovenstående JavaScript-fejl.

**Comment by JosefAssad** [comment]
Den javascript fejlmeddelelse, den bliver vist i selve browserområdet? Hvis ja så tror jeg du har en form for js debugging aktiv. Fejlen ligner #157 og burde ikke vises i browseren (kun i js console).

**Comment by danchr** [comment]
Ja, jeg ser den i browserkonsollen — men måske er det ikke den der er det egentlige problem. Det er i hvert fald at ingen sider viser noget indhold:

![screen shot 2016-11-21 at 15 09 02](https://cloud.githubusercontent.com/assets/59300/20485574/8146f684-affc-11e6-9a61-96a184488397.png)

**Comment by JosefAssad** [comment]
Har du konfigureret `$wgServer` i `LocalSettings.php` ?

https://github.com/JosefAssad/SeMaWi/blob/master/docker/README.md#obligatory

**Comment by danchr** [comment]
> Har du konfigureret $wgServer i LocalSettings.php ?

Nej, den er efterladt som standardværdien `172.17.0.1` — hvilket burde virke. Opdagede lige noget interessant: hvis jeg tilføjer `?debug=true` til adressen så virker siden. Jeg får endnu flere fejl, og i indstillinger kan jeg ikke vælge de enkelte emner, men jeg kan i det mindste se indholdet i wikien.

**Comment by JosefAssad** [comment]
> Nej, den er efterladt som standardværdien 172.17.0.1 — hvilket burde virke

172.17.0.1 er ikke en standardværdi for den variabel. `$wgServer` skal som regel sættes til wiki'ens "eksterne" IP adresse.

**Comment by danchr** [comment]
Aaah, det var det! Tak — og undskyld forstyrrelsen! (Det virker lidt fjollet at MediaWiki ikke kan udlede URLen fra de HTTP requests den får, men det er vel hinsides din kontrol…)

Et lille forslag: Hvis du kombinerer _Running a container for testing/development_ med _Post deploy configuration_ og fremhæver sætningen om `$wgServer` på samme måde som databaseindstillingerne, tror jeg det vil mindske sandsynligheden for at andre begår samme fejl som mig.

**Comment by JosefAssad** [comment]
Ja der er en del ting der er rigtig fjollede ved MW, just wait. :)

Angående det med at fremhæve sætningen om `$wgServer`: pull request please. Jeg ved godt dokumentationen er elendig. :)
