### ISSUE TITLE
Ændring af navn på system

### ISSUE THREAD

**Issue by ballerupgis** [JosefAssad/SeMaWi#18]
Når der oprettes et nyt system angives et navn for siden, hvorefter der igen angives et navn i form. Hvordan ændres navnet for siden, og ville det ikke være nok med et navn?

**Comment by JosefAssad** [comment]
Ja, din observation er korrekt. Jeg har selv tænkt lidt over det, blandt andet da jeg implementerede datamodellen.

Der er to muligheder her, entan at vi fjerner navn feltet eller lader det blive, begge har pluser og minuser.

# Fjern feltet

På plussiden så bliver form'en enklere. Det er altid en fordel der ikke skal undervurderes. Ulemperne er lidt mere teoretiske, men jeg kan umiddelbart finde på to:

1. Hvis der er queries i systemet som anvender Property::systemNavn så vil de skulle findes og rettes
2. Hvis der er systemer som muligvis kendes ved et navn som er forskellig fra systemets formelle navn så mister man mulighed for at gemme denne information. Langt de fleste systemer kaldes jo det de hedder, men det er ikke umuligt at et system kaldes i daglig tale noget andet end hvad det i virkeligheden hedder. :) Det kunne være et eksempel med DUBU; de fleste ville søge i SeMaWi efter "DUBU" men det formelle navn er Digitalisering på børn- og ungeområdet.

# Feltet bliver

På plussiden så har vi mulighed for at adressere use cases hvor systemer omtales med et navn der er forskellig fra systemets formelle navn.

På minussiden så har vi et ekstra felt som vi ved ikke rigtig behøves for langt de fleste systemer. Det er ikke et kolossalt minus da feltet ikke er obligatorisk, men det er alligevel et minus.

---

Rent teknisk så er det ikke traumatisk at fjerne feltet. Men det er altid nemmere ikke at ændre kode end at ændre kode. :)

Hvad siger i til den korte analyse?

**Comment by JosefAssad** [comment]
En yderligere mulighed er, at beholde feltet SystemNavn, men at gøre det optionelt og forklare hvordan det bruges med placeholder således:

![placeholder](https://cloud.githubusercontent.com/assets/1040956/9490535/bd8a1dc0-4be8-11e5-807a-bcf0e05c927e.png)

Desuden er der implementeret hjælpetekst fra #17 som også skulle hjælpe.

Det bliver måden jeg implementerer nu. Jeg er 100% for at gøre forms enklere men inden vi kan smelte sidetitel og SystemNavn sammen må vi finde på en bedre måde at navngive sider. Ideelt ville sidetitler være autogenereret fra systemnumre (fx sidetitel som "System_100432"), men det er langt fra alle systemer der har angivet nummer.

**Comment by ballerupgis** [comment]
En meget vigtig pointe, som også har en organisatorisk udfordring....jeg overvejer...
