### ISSUE TITLE
Maintenance extension

### ISSUE THREAD

**Issue by mariushart** [JosefAssad/SeMaWi#186]
Kunne det være en god ide at anvende Maintenance extension for automatisk runJobs?

https://www.mediawiki.org/wiki/Extension:Maintenance

**Comment by JosefAssad** [comment]
Jo, det har jeg ikke noget imod. Den ser ikke ud til at medføre databaseændringer, så det er godt.

Den giver ikke adgang til ´rebuildall.php´ scriptet, lidt af en begrænsning. I mange tilfælde hvor vi ville ønske at køre `runJobs.php` manuelt ville vi gerne køre `rebuildall.php` inden, da det typisk drejer sig om større antal sider.

Men nogle gange hvor der er indirect property kalkulationer kunne det være nyttigt. Jeg inkluderer den i 2017_01 releaset.

**Comment by JosefAssad** [comment]
@baffioso @ClockEnd thumbs up?
