### ISSUE TITLE
headertabs på geodata

### ISSUE THREAD

**Issue by JosefAssad** [JosefAssad/SeMaWi#188]

**Comment by JosefAssad** [comment]
Har i et bud på, hvordan felterne på geodatasider skal deles op i faneblade? Der er i øjeblikket følgende felter:

* Titel
* Beskrivelse
* Skema
* Tabelnavn
* Laggruppe
* SRID
* Geometritype
* KLE-numre
* URL
* GUID
* Dataansvarlig

**Comment by baffioso** [comment]
Tror det er fint med ovenstående i tab1. Når vi får trukket kolonner fra tabeller vha ExternalData kan de komme i tab2.

**Comment by JosefAssad** [comment]
Alrightie. Tilføjer så dependency på #146
