### ISSUE TITLE
kobling mellem systemer og geodata tabeller

### ISSUE THREAD

**Issue by JosefAssad** [JosefAssad/SeMaWi#19]

**Comment by JosefAssad** [comment]
Giver det mere mening for jer, at man specificerer under et system hvilke geodata tabeller det anvender, eller at man specificerer under en geodatatabel hvilke systemer det bliver brugt i?

Eller er det 50/50?

**Comment by ballerupgis** [comment]
Umiddelbart vil jeg mene, at det er bedst at systemet angiver hvilke (geo)data det bruger/redigerer/leverer: Vi har eksterne systemer som leverer data til GC2 via services, derfor mener jeg det vil være mest korrekt, hvis systemerne 'redegjorde' for deres dataanvendelse

**Comment by ballerupgis** [comment]
Swift, done and dusted

**Comment by JosefAssad** [comment]
![anvendte](https://cloud.githubusercontent.com/assets/1040956/9466359/97016d5c-4b34-11e5-9ac6-6b138ed72016.png)

**Comment by ballerupgis** [comment]
Spot on m8
