### ISSUE TITLE
Henvisninger der ikke virker

### ISSUE THREAD

**Issue by ClockEnd** [JosefAssad/SeMaWi#190]
Under Data > Bymidtemonitering har jeg henvisninger til 'Rapporten er her: Fil:Discountbutik på Posthusgrunden, Ballerup Kommune, ICP, 17.juni 2016.pdf' som ikke åbner - får følgende:
Not Found
The requested URL /images/7/76/Discountbutik_pÃ¥_Posthusgrunden,_Ballerup_Kommune,_ICP,_17.juni_2016.pdf was not found on this server.
Apache/2.4.10 (Debian) Server at 10.192.224.40 Port 12345

Det er bare inden jeg lægger yderligere dokumentation op. Og der er sikkert flere henvisninger som ikke er aktive.
Please advise

**Comment by JosefAssad** [comment]
Kiggede på serveren og den var der godt nok ikke, men fiskede den ud af en lokal backup her. Jeg tror det er fra dengang vi udførte opgradering fra ikke-docker til docker, dengang var Søren hurtig til at melde om manglende filer som jeg havde overset. Hvis jeg har misset flere sig endelig til, overgangen fra ikke-docker til Docker var ret kompleks og der kan være enkelte ting som ligger i backup og venter på at blive husket.

**Comment by ClockEnd** [comment]
Løber lige igennem - mangler:
Fil:BallerupCentret 2016 09 30.pdf
Fil:Bymidte cvr2016.ods

**Comment by JosefAssad** [comment]
Super. Jeg kan også sammenligne filerne fra backuppet så skulle vi være på den sikre side.

On February 14, 2017 11:01:19 AM GMT+01:00, Lars Dalgaard <notifications@github.com> wrote:
>Løber lige igennem - mangler:
>Fil:BallerupCentret 2016 09 30.pdf
>Fil:Bymidte cvr2016.ods
>
>-- 
>You are receiving this because you were assigned.
>Reply to this email directly or view it on GitHub:
>https://github.com/JosefAssad/SeMaWi/issues/190#issuecomment-279662374

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by JosefAssad** [comment]
Roger, begge filer er hjemme igen. :) checker om jeg kan spotte flere.

**Comment by baffioso** [comment]
Vi lukker denne midlertidigt, og kan åbnes igen hvis der findes flere døde links

**Comment by JosefAssad** [comment]
Har lige sammenlignet med backup og kan umiddelbart ikke spotte yderligere manglende filer. Should be fine.
