### ISSUE TITLE
Kolonneberskrivelse for data

### ISSUE THREAD

**Issue by baffioso** [JosefAssad/SeMaWi#191]
Vi ønsker kolonnebeskrivelse for geodata/data ved brug af eksterne databasekald.

Se #146

**Comment by JosefAssad** [comment]
SÅ sker der noget. :) Se http://10.192.224.40:12345/index.php/SeMaWi/Opkobling_til_SQL_Server

Planen nu er at lappe implementere på containeren, og samtidig opdatere kodebasen her så næste version understøtter det natively.

**Comment by JosefAssad** [comment]
Serveren kan nu snakke med en SQL Server (se #193 ) og ExternalData og OdbcDatabase udvidelserne er installeret i SeMaWi imaget. Jeg har testet og kunne godt få en end-to-end (kald fra ExternalData som viser SQL Server data i mediawiki) til at fungere, så nå må det være et spørgsmål om, hvad for noget data vi skal læse fra SQL Server og hvordan det skal modelleres.

Da jeg ikke kender meget til GIS og næsten intet til jeres SQL Server assigner jeg til @baffioso :)

**Comment by baffioso** [comment]
@JosefAssad vi er første omgang kun interesseret i at hente data fra PostgreSQL som også kører med ExternalData. Tror vi skal finde en dag og kigge på issued sammen. MSSQL kan nok blive aktuelt på et senere tidspunkt.

**Comment by JosefAssad** [comment]
Den her burde vi kunne lukke nu, efter vi viser geodatakolonner?
