### ISSUE TITLE
Mangler brugervenlig besked når der oprettes side som allerede eksisterer

### ISSUE THREAD

**Issue by baffioso** [JosefAssad/SeMaWi#195]
Prøvede at oprettet BBR som data, men det eksisterer allerede som system.
![image](https://cloud.githubusercontent.com/assets/7534153/24191096/f28f555a-0eea-11e7-8c0b-4a8f86d5a5d0.png)

**Comment by JosefAssad** [comment]
Yeah det her er faktisk et bug og ikke en manglende besked. :) Har undersøgt lidt, jeg tror det er en af de småting som fløger af skiftet fra SemanticForms til PageForms (se #171 ). Fejlen opstår heldigvis ikke i dev versionen, har lige testet.

Er det noget der kan vente til dev versionen lanceres?

I øvrigt kan jeg anbefale at navngive sider med sammenfaldende titler efter kategori hvor nødvendigt (eksempel: BBR_(System) og BBR(Data) )

**Comment by baffioso** [comment]
Det haster ikke. Og vi omdøber bare siderne

**Comment by JosefAssad** [comment]
Overgangen til PageForms er nu færdig, og vi rullede nogle versioner ud i mellemtiden. Jeg har testet og kan ikke genskabe problemet. Skulle være ok nu. :)
