### ISSUE TITLE
Gennemgang af Projekter

### ISSUE THREAD

**Issue by ClockEnd** [JosefAssad/SeMaWi#197]
Mangler et fix/review på kategorien Projekter

**Comment by JosefAssad** [comment]
9.8/10

Manglede nogle kategorier, et property havde forkert navn, og så havde jeg bidraget med et fejlagtigt og overflødigt "/" tegn i skabelonen. :)

Luk bare denne issue hvis du er tilfreds med måden denne klasse fungerer nu. Rigtig flot og velintegreret med resten af dataelementerne!

**Comment by ClockEnd** [comment]
Excellent :-)
