### ISSUE TITLE
Kategori:Geodata viser kun få tabeller

### ISSUE THREAD

**Issue by baffioso** [JosefAssad/SeMaWi#199]
Man kan godt fremsøge de andre tabeller, men fremgår ikke af listen

![image](https://cloud.githubusercontent.com/assets/7534153/24791785/c93eaece-1b7b-11e7-974f-9f2ac71a2f99.png)

**Comment by JosefAssad** [comment]
Yep, kan se at runJpbs.php cronjobbket ikke har kørt. Skulle være nemt at rette. :)

**Comment by JosefAssad** [comment]
Hm kan ikke se noget galt i cronjobbet. Jeg har givet det et manuelt spark, kan i sige til hvis i ser samme problem igen på mandag?

**Comment by ClockEnd** [comment]
Ser ud til det kører
