### ISSUE TITLE
Betinget formulardesign

### ISSUE THREAD

**Issue by baffioso** [JosefAssad/SeMaWi#204]
Vi er interesseret i betinget formulardesign, hvor feltet STORM-opmærkning bestemmer hvilken sub-form der skal anvendes. Ideen er at vælges eksempelvis STORM=GIS vises specifikke meta-informationer om dette område, f.eks. Geografisk identifikation og Geodatarelation. Formålet er at afprøve testen om at STORM kan anvendes til det formål.

I første omgang snakker vi om en prototype, hvor vi vælger et par STORM-områder, f.eks. ”GIS”, ”Master data” og måske ”Selvbetjening”.

Første niveau af STORM lagt ind (der er to niveauer: http://arkitekturguiden.digitaliser.dk/storm )
![image](https://cloud.githubusercontent.com/assets/7534153/25170990/ac7997b6-24ec-11e7-9f31-98ac79965946.png)

**Comment by JosefAssad** [comment]
Er det tanken, at man har en form med felter som tilsammen danner et "superset", og at man viser eller skjuler felter alt efter den valgte værdi i en dropdown? Har jeg forstået korrekt?

**Comment by baffioso** [comment]
Ja, sådan har jeg forstået. (Det er et ønske fra Leif)

**Comment by JosefAssad** [comment]
Tror godt det kan gøres. Scheduler lidt eksperimentationstid til det!

**Comment by JosefAssad** [comment]
Nu har jeg eksperimenteret lidt. Det klares vha. `show on select` parameter til den dropdown som afgør hvilke registertype der er tale om.

Har i en case? Det jeg skal bruge er:

1. En form som danner et superset som rummer alle de felter kan vises.
2. Udpegning af "master feltet"; nok en STORM dropdown, måske i "Data" klassen?
3. En "list of lists" som dokumenterer hvilke felter skal vises for hvilke værdier, inklusiv de felter som skal vises for alle værdier af STORM feltet. for eksempel:

* Værdi 1 i STORM feltet
    * Felt A vises
    * Felt B vises
    * Felt E vises
* Værdi 2 i STORM feltet
    * Felt C vises
    * Felt D vises
    * Felt E vises

**Comment by ClockEnd** [comment]
Jeg tjekker STORM-kataloget

**Comment by ClockEnd** [comment]
Det er denne, hvorfra leif peger på å test vedr. ”GIS”, ”Master data” og måske ”Selvbetjening” - fanen Taxonomi
[storm2_2_kladde_0_10-1.xlsx](https://github.com/JosefAssad/SeMaWi/files/970278/storm2_2_kladde_0_10-1.xlsx)

**Comment by JosefAssad** [comment]
Jeg går ud fra, at det er i modellen "Data" hvor vi skal eksperimentere med betinget visning af felter?

altså, afhængig af værdien i feltet "STORM-opmærkning" vises eller skjules forskellige felter?

Hvis det er rigtigt så burde det ikke være svært. Jeg kan kopiere form siden til en testversion og implementere betinget feltvisning der. Vi skal bare finde ud af, for alle mulige STORM værdier, hvilke øvrige felter skal vises og hvilke øvrige felter skal skjules, og hvilke felter bare skal vises uanset STORM værdi.

Skal vi starte med, at de to felter "Gisident" og "Relateret geodata" kun vises hvis vi vælger STORM opmærkning "S: GIS"?

**Comment by ClockEnd** [comment]
Det lyder som en god ide, lad os køre med det. Så kan vi få IT-dig på banen til at kvalificere og prioritere de resterende dele

**Comment by JosefAssad** [comment]
Ser umiddelbart ud til at fungere ret godt. Jeg har oprettet et kopi af Form:Data under navnet form:DataTest.

Prøv at åbne formen [her](http://wiki/index.php/Form:DataTest) og opret en testside. Derefter i feltet "STORM-opmærkning" vælg "S: GIS", så kan i se at de to geodata felter kun bliver vist når det er den værdi man har valgt der.

vi kan sagtens flytte den form så den erstatter den gamle, men jeg forestiller mig, der er flere felter der skal vises eller skjules afhængig af STORM klassifikation.

Hvad siger i?

**Comment by ClockEnd** [comment]
Excellent.... Jeg tager fat i Leif

**Comment by JosefAssad** [comment]
Jeg har i mellemtiden produceret en lille prorotype hvor man kan drille ned i STORM hierarkiet, men den må vente lidt. Årsagen er, at denne feature bruger [Semantic forms Select](https://www.mediawiki.org/wiki/Extension:Semantic_Forms_Select) og vi har en issue om at integrere den udvidelse her: #92 . Men som følge af, den forvirring jeg regnede med ville ske efter #171 er der opstået en bug i den udvidelse som jeg følger op på her: https://github.com/SemanticMediaWiki/SemanticFormsSelect/issues/64

Det er ikke en blocker for yderligere arbejde på betinget formulardesign, bare en lille forbedring som vi kan bruge når det fulde STORM skal ind og der kommer mange betingede felter.

**Comment by ClockEnd** [comment]
Eksemplet er fint, det kan vi begynde med og det viser at STORM kan omfavnes og anvendes med mening i Semantic Mediawiki

**Comment by JosefAssad** [comment]
Jeg har opdateret form:Data nu så den bruger den betingede visning af GIS felter. Glæder mig til, at vi opdeler flere felter op i STORM-kategorier. :)
