### ISSUE TITLE
Fatal error ved oprettelse af ny brugerkonto

### ISSUE THREAD

**Issue by ClockEnd** [JosefAssad/SeMaWi#205]
Fatal error: Class 'Net_SMTP' not found in /usr/share/php/Mail/smtp.php on line 346 @JosefAssad

**Comment by JosefAssad** [comment]
Ah. Hm hvorfor bliver det bibliotek ikke installeret? Har installeret fra Debian's repos nu, kan du sige om det løser problemet? Brugeren burde være oprettet, det burde kun være mail som ikke kan sendes ud.

Hvis ikke det løser problemet så instalerer jeg Net_SMTP direkte fra pear...

**Comment by ClockEnd** [comment]
Skal jeg oprette endu en ny bruger eller hvordan tester jeg bedst?

**Comment by JosefAssad** [comment]
Jo det er nok den nemmeste måde at teste. Men det har jeg lige selv gjort og ud fra hvad jeg kan se fungerer det fint nu.

Du må gerne double checke hvis du har lyst, ellers slap dat close button. :)
