### ISSUE TITLE
Kolonner listes ikke for geodata

### ISSUE THREAD

**Issue by baffioso** [JosefAssad/SeMaWi#206]
![image](https://cloud.githubusercontent.com/assets/7534153/25330101/bb833e60-28de-11e7-9b1b-ad65a9eaa3c6.png)

**Comment by JosefAssad** [comment]
Ja det kan jeg godt se. På backended suger apache 100% CPU når man slår geodata sider op, så jeg tænker det kunne give mening at fjerne DB kaldet foreløbigt og teste med det om aftenen så man ikke forstyrrer arbejde.

Lidt skørt når det nu fungerede fint sidst.

**Comment by JosefAssad** [comment]
Jeg tror der foregår en form for caching i headertabs. Jeg har flyttet db koden ud af headertabs og der fungerer det fint, ser det ud til. Jeg foreslår vi holder det der og så tager jeg en snak med extension udvikleren og ser hvad de har at sige.

**Comment by JosefAssad** [comment]
[Upstream](https://www.mediawiki.org/wiki/Topic:Tpa9n0v3le7s9zym).

**Comment by baffioso** [comment]
Fedt Josef
