### ISSUE TITLE
Fejl ved upload af fil

### ISSUE THREAD

**Issue by baffioso** [JosefAssad/SeMaWi#209]
Får denne fejl når jeg prøver at uploade 2 mb pdf
![image](https://cloud.githubusercontent.com/assets/7534153/25905510/7dbecd30-35a2-11e7-8794-edad01c73f0e.png)

**Comment by JosefAssad** [comment]
Kan du forsøge igen og se om fejlen er væk? Har indstillet nginx således at uploadgrænsen er på 50M samme som i `php.ini`.

**Comment by ClockEnd** [comment]
Får 502 Bad Gateway nginx/1.6.2 ved forsøg på login til gc2

**Comment by JosefAssad** [comment]
Jeg checkede gc2 i går efter at have tweaket nginx proxy'en og den åbnede fint. Lige nu kan jeg godt se den fejl du beskriver.

Har kigget på serveren og docker siger at gc2core containeren gik ned for en time siden. Der har jeg ikke været inde og lave noget. Jeg kan ikke udelukke at det kunne være noget i nginx alligevel, men jeg har lidt på fornemmelsen at der er noget ved gc2core containeren. skriver lige til Martin.

**Comment by ClockEnd** [comment]
Har du set Martins mail 2017/05/15 09:24?

**Comment by JosefAssad** [comment]
Dette viste sig at være driftssag.
