### ISSUE TITLE
Fritekst i headertabs

### ISSUE THREAD

**Issue by baffioso** [JosefAssad/SeMaWi#211]
Det lader til at fritekst-dokumentationen kommer til at indgå i tabs.  Skal nok rettes lidt i template

![image](https://cloud.githubusercontent.com/assets/7534153/26831941/26f42c70-4ace-11e7-83da-437253440a19.png)

**Comment by JosefAssad** [comment]
Det tog alt for lang tid før jeg spottede rookie fejlen. :) (manglede at lukke en div i GC2 kortindlejringsafsnittet)

**Comment by baffioso** [comment]
Kan godt stamme fra da jeg prøvede at fikse bug i kort indlejret i tab pane

**Comment by JosefAssad** [comment]
Jo jeg tror det starterede [her](http://wiki/index.php?title=Skabelon%3AGeodata&type=revision&diff=209660&oldid=209659). Men det er en ret lille ting. Selv om formattering var lidt ulogisk så fungerede det med faneblade alligevel, Bedste bevis er at det har taget os ret lang tid at opdage. :)

**Comment by baffioso** [comment]
Tjek
