### ISSUE TITLE
Indholdsfortegnelse for fritekst er væk

### ISSUE THREAD

**Issue by baffioso** [JosefAssad/SeMaWi#212]
Lader til der ikke længere er indholdsfortegnelse øverst i fritekst. 

Se f.eks. http://wiki/index.php/Geodata_Armaturplacering

**Comment by JosefAssad** [comment]
Ja det er rigtigt. Var den der før?

Normalt i mediawiki så indsætter systemet automatisk en indholdsfortegnelse hvis man overstiger et vist antal overskrifter, men man kan også manuelt indsætte indholdsfortegnelse ved at skrive `__TOC__`. Det har jeg gjort på den side og det for indholdsfortegnelsen frem igen.

Så er det bare et spørgsmål om, hvis dne var der før, hvorfor den ikke er der længere. Har nemlig ikke pillet i nogen config...

**Comment by baffioso** [comment]
Kunne være fint at få den automatiske funktion tilbage når den overstiger x antal overskrifter.

**Comment by JosefAssad** [comment]
Enig. Ser du manglende TOC andre steder? Vil gerne finde ud af, hvornår den forsvinder.

**Comment by baffioso** [comment]
Troede først det kun ramte geodata pga. link til guid dokumentation, men herunder er der også eksempel på system, som ikke har indholdfortegnelse

http://wiki/index.php/Geodata_Administrative_vejdata
http://wiki/index.php/QGIS

**Comment by JosefAssad** [comment]
Jeg har gravet lidt. Det sker på sider hvor vi anvender [HeaderTabs](https://www.mediawiki.org/wiki/Extension:Header_Tabs). Det burde jeg have gættet, fordi HeaderTabs bruger jo H1 overskrifter til at markere tabs, og H1 overskrifter indgår i indholdsfortegnelser også.

Det viser sig, at der er en HeaderTabs indstilling som hedder [$wgHeaderTabsDisableDefaultToc](https://www.mediawiki.org/wiki/Extension:Header_Tabs#.24wgHeaderTabsDisableDefaultToc) som deaktiverer `__TOC__` på sider som anvender HeaderTabs. Når man slår den fra så dukker indholdsfortegnelsen godt nok automatisk op igen, men den gør det helt i toppen af siden i stedet for under HeaderTabs kassen hvor den burde være. Så den løsning duede ikke.

I stedet for har jeg tilføjet `__TOC__` for Geodata og Systemer og det ser ud til at fungere fint.

* [Skabelon:System diff](http://wiki/index.php?title=Skabelon:System&curid=50&diff=230339&oldid=227903)
* [Skabelon:Geodata diff](http://wiki/index.php?title=Skabelon:Geodata&curid=6318&diff=230337&oldid=225808)

Så må vi bare huske at indsætte indholdsfortegnelse eksplicit i skabeloner som anvender HeaderTabs.

**Comment by baffioso** [comment]
Fedt
