### ISSUE TITLE
Oprette kontraktkategori

### ISSUE THREAD

**Issue by baffioso** [JosefAssad/SeMaWi#214]
Vi har snakket om at løsrive kontraktoplysninger fra system kategorien og lave en separat kontraktkategori: 

Udkast til model:
![image](https://user-images.githubusercontent.com/7534153/27324131-6dd23f66-55a4-11e7-9366-e66acc841d7a.png)

**Comment by JosefAssad** [comment]
Det kan sagtens implementeres. Vi skal dog afklare hvad nogle af felterne betyder.

Er salgs- og leveringsbetingelser sådan noget freeform tekst?

"Firma", går ud fra, at det peger på klassen "Leverandør"? I så fald skal vi fjerne det felt også fra systemklassen.

Opsigelsesvarsel skal vi tænke lidt over. Hvis vi implementerer den, så kommer der et ønske om automatiske notifikationer når en kontrakt nærmer sig opsigelsesvarsels tidspunktet. Det er desværre ikke helt trivielt at implementere. en alternativ mulighed er, at anvende et felt "Sidste frist for opsigelse", så kan vi se om vi kan strikke en query sammen som henter de kontrakter som er 1 måned (for eksempel) fra sidste frist for opsigelse, og lister dem i en rapport.

Alt andet i oventsående ser standard og ret logisk ud. :)

**Comment by JosefAssad** [comment]
Erstattes af #220
