### ISSUE TITLE
Indhent data fra Kitos

### ISSUE THREAD

**Issue by baffioso** [JosefAssad/SeMaWi#215]
Første skridt mod #97 

Vi skal se på at få etableret hensigtsmæssig import/synkronisering til Wiki.
Primært med henblik på at sikre, at primærnøgle anvender enten UUID eller internt KITOS-ID.
Desuden se på muligheden for at anvende SAML-token til authentificering og runtime provisionering af brugere. Det er vores foretrukne authentificeringsmetode.
(Det betyder automatisk oprettelse, hvis en bruger ikke findes i forvejen).
F.eks. https://www.mediawiki.org/wiki/Extension:SAMLAuth 
Kontakt Niels Erik Nordberg (neno) for yderligere information fsva. føderation.

Vi har aftalt at vi på den korte bane opretter en parallel-register i Wiki til KITOS-systemerne. (Skal vi allerede nu indtænke import af leverandører og kontrakter?). Vi skal have oprettet form og template som passer til datastrukturen, og hvor de importerede informationer IKKE kan redigeres i GUI'en.

Ballerup kommune er indstillet på at implementere datamodellen i wiki, hvis det giver mening forud for import.

Efterfølgende skal vi aftale hvordan vi får de to registre flettet sammen til et fælles system-register.

Der er allerede oprettet en MariaDB så der kan tilgås en tabel med systemer.

**Comment by JosefAssad** [comment]
Lad mig se om jeg kan nedbryde det i mindre bidder.

# SAML Login

Bruger i SAML til SSO og ikke AD? Ud fra hvad jeg kan finde er der en extension som ligner den kan det, men den er beta så det skal nok testes grundigt igennem først. Det er ikke helt trivielt at implementere; kan sagtens lade sig gøre bare ikke en fem minutters opgave. :) Kræver også en del analyse.

# Datamodel

Ja jeg synes på den korte bane giver det mening at parallelregistrere KITOS datamodel elementer adskilt fra eksisterende leverandører og systemer. Så kan vi stille og roligt arbejde hen mod, at ende med kun den ene eller den anden.

Er det fra mariadb vi skal indlæse? For så kan vi konvertere tabellen (det er 1 tabel, yes?) til en klasse så er det klaret.

Skal samme gøres for Leverandører og Kontrakter?

# Read-only

Problematisk. Den oplagte funktion i mediawiki er noget der hedder "protect", men den kan ikke indstilles så den påvirker et helt Kategori. Det findes der så vidt jeg kan se heller ikke extensions til.

Hvis jeg skal tænke på en lavteknologisk løsning, så kunne vi overveje om det ikke er tilstrækkeligt at siderne jo bare bliver overskrevet hver gang man indlæser Kitos objekter? Præcis som det der sker med Geodata sider i øjeblikket (ikke de tilknyttede dokumentations undersider).

# Generelt

Hvordan ser det ud tidsmæssigt? Giver det mening at sætte dette som fokus i anden halvdel af året?

**Comment by lodahl** [comment]
SAML Login
Ja vi foretrækker SAML-token til SSO og run time provisionering.

Datamodel
Enig.
Leverandører og kontrakter kommer senere, da vi ikke har en brugbar ID i KITOS. Vi kravler først, og løber maraton senere.

Read-only
Acceptabelt på kort sigt.

Generelt
Det afhænger af mange parametre. SAML-integrationen haster ikke. Indlæsning af Systemerne forestiller vi os kommer til at ske hen over sommeren. MariaDB-databasen er på plads.

**Comment by JosefAssad** [comment]
Lyder rigtig forniftigt @lodahl . Tror godt vi allerede her i juli vil kunne begynde at kigge på mariadb serveren. :)

JEg har udført lidt triage og splittet denne issue op i delopgaver. Se lige om i synes der mangler noget og hvis ikke der gør så kan vi lukke denne og arbejde videre med de 5 issues som den er delt op i.
