### ISSUE TITLE
datamodel for internt aftalt handlinger

### ISSUE THREAD

**Issue by JosefAssad** [JosefAssad/SeMaWi#22]
et meget enkelt ”meta system” til at holde overblikket og følge op på internt aftalt handlinger i centeret.

- Hvorfor
- Hvad
- Hvem
- Hvornår
- Fremdrift

**Comment by lenethystrup** [comment]
God ide med at lægge en prototype på en dev server. 
Jeg tænker at involvere andre "brugere" i udviklingen - og de bliver nok overvældede, hvis der ligger alt muligt andet de ikke kender til.
