### ISSUE TITLE
Geodata ikke med i Wiki

### ISSUE THREAD

**Issue by ClockEnd** [JosefAssad/SeMaWi#225]
Jeg oprettede to geodatafiler i gc2 i fredags (bilejerskab og biladgang) i skema  _05_ men de er ikke blevet opretet i SeMaWi, pls advise

**Comment by JosefAssad** [comment]
Ah yes my bad, cronjobbet pegede på den gamle container. Det bliver godt når vi får den nye docker-compose udgave rullet ud da det giver os lidt mere stabilitet i denne forbindelse.
