### ISSUE TITLE
Fejlbesked ved brugeroprettelse

### ISSUE THREAD

**Issue by baffioso** [JosefAssad/SeMaWi#228]
Fik denne:

Fatal error: Class 'Net_SMTP' not found in /usr/share/php/Mail/smtp.php on line 366

**Comment by JosefAssad** [comment]
Yeah den har vi set før, der er en [fix i dev](https://github.com/JosefAssad/SeMaWi/blob/dev/2017_01/composer.local.json#L9) men ikke i prod endnu. Rimelig irriterende, beklager.

Kan i prøve nu? Brugeren burde alligevel være oprettet, den kunne bare ikke sende mail ud.

**Comment by ClockEnd** [comment]
@HansSkaarup

**Comment by HansSkaarup** [comment]
Det virkede fint da jeg prøvede at oprette mig nu.

**Comment by JosefAssad** [comment]
Super, takker!
