### ISSUE TITLE
Kontrakt kategori

### ISSUE THREAD

**Issue by baffioso** [JosefAssad/SeMaWi#230]
Vi har snakket om en kontrakt kategori til registrering af alt andet end IT-kontrakter (De kommer fra Kitos). 

Properties |  
-- | --
Relation til system |  
Kontraktkategori/type | Lejekontrakter, Brugsaftale, Konsulenter, Abonnementer, Købsaftaler, Samarbejdsaftaler,
Salgs og leveringsbetingelser |  
Beskrivelse |  
Firma |  Relation til Leverandør
Anskaffelsessum |   
Årlig omkostning |  
Skæringsdato |  
Opsigelsesvarsel |  
Kontraktdato |  
Bindingsperiode |  
Journalnummer i SBSYS |  

Fra Anskaffelsessum og ned kan vi tage fra System-kategorien da de nok ikke skal bruges der. Vi skal lige se på om vi omdøber eller om der går data tabt.

**Comment by ClockEnd** [comment]
Måske vi kunne koge det yderligere ned, når nu der ikke er binding til IT-kontrakter?
[OMRÅDE]
[FORMÅL]
[Opgaveejere NAVN]
[PRIS]
[LØBETID]
[OPSIGSELSESFRIST]
?

**Comment by ClockEnd** [comment]
Vi er nået frem til følgende efter møde den 15.8:
[OMRÅDE]
[FORMÅL]
[Opgaveejere NAVN]
[DRIFTSPRIS]
[ETABLERINGSPRIS]
[LØBETID]
[OPSIGSELSESDATO]
[DATO]
@lenethystrup og jeg har diskuteret om vi kan genbruge properties fra IT-kontraktdelen, eller om det er nødvendigt at oprette nye?

**Comment by JosefAssad** [comment]
Hm. Ud fra hvad jeg kan se har SeMaWi ikke ItKontrakt endnu som klasse. Så jeg tror ikke der er properties man kan hente derfra; måske mener i [Kontrakt klassen](http://wiki/index.php/Skabelon:Kontrakt) som @baffioso har oprettet?

Hvis vi tænker lidt mere strategisk, så ja tanken har været at der skal komme en klasse til it kontrakter hentet fra KITOS svjh. Det ville undre mig en del hvis ikke der var felter i den som også fandt anvendelse i den mere generelle Kontrakt klasse, som fx. parter, varighed, opsigelse, osv.

Men, for at i ikke havner i den situation at i ikke for Kontrakt klassen oprettet fordi i venter på ItKontrakter at oprettes, så er det måske fornuftigt at i bare kører med jeres Kontrakt klasse, og så kan der tilrettes senere når ItKontrakt implementeres og der kan identificeres fælles felter.

Hvis helt praktisk der er felt i Kontrakt klassen som skal ændres fra et property til et andet fælles så er det ikke så svært, man tilrettet bare i skabelonen og kører en `runJobs.php` for god ordens skyld. :)

**Comment by ClockEnd** [comment]
Thx, m8

**Comment by lenethystrup** [comment]
Vi har nu på i "Kontrakt" klassen oprettet  KLE og Journalnummer felter. Vi har brugt properties fra "System" klassen. ( det er den I kalder ITsystemer ?)
Spørgsmålet er om det giver problemer at dele properties i flere klasser ifht søgninger ?
Eller kan vi klare den ved at skrive [[Category:SeMaWi]] [[Category:kontrakt]] i disse properties?

**Comment by JosefAssad** [comment]
Det er et godt spørgsmål. I praktis hvis man genbruger property for two klasser så skal man i princippet bare sørge for at afgrænse sin søgning lidt mere nøje.

For eksempel, hvis man genbruger et property "Alder" for to klasser "Kat" og "Hund" så duer det ikke længere at man bare søger på `[[Alder::3]]`. så skal det hedde `[[Category:Hund]] [[Alder:3]]` eller `[[Category:Kat]] [[Alder:3]]`.

**Comment by lenethystrup** [comment]
Jeg har i alle elementerne (properties,  template og  form)i "Kontrakt" klassen- indskrevet [[category:Semawi]] og [[category:Kontrakt]] - det lærte du mig vist engang :=) Er det rigtigt gjort?
Hvordan får vi lavet en liste over alle kontrakter - uden at vi får vist properties, template og form med i oversigen?

**Comment by JosefAssad** [comment]
Det er *næsten* rigtigt. :)

En vigtig detalje at huske er, at alt i semantic mediawiki er en wikiside, også vores modeller.

Så det jeg plejer at gøre, når jeg skal oprette en klasse "Kat" er, at markere de sider der indgår i selve klassen som `[[Category:Kat-Datamodel]]` og de sider som oprettes vha. klassen som `[[Category:Kat]]`.

Din use case er et godt eksempel på hvorfor vi gør det. :)

Hvor det er vi skriver de kategorier ind kan af og til være forvirrende eller nem at glemme. Det drejer sig om skabelonen; i skabelonen har vi alt det der hejs med `includeonly` og `noinclude`. I `noinclude` er den tekst som kun vises når vi kigger på selve skabelonen, så det er der vi skriver `[[Category:Kat-Datamodel]]`. Under `includeonly` er den tekst som kun vises når en side *anvender* skabelonen, så det er der vi skriver `[[Category:Kat]]`.
