### ISSUE TITLE
Bedre sidetitler til Geodata tabeller

### ISSUE THREAD

**Issue by JosefAssad** [JosefAssad/SeMaWi#25]
Sidetitler på geodata wikisider er i øjeblikket ret grimme.

![geodata-grimme-sidenavne](https://cloud.githubusercontent.com/assets/1040956/9466397/debfc3d2-4b34-11e5-9893-552f7706f0ad.png)

**Comment by ballerupgis** [comment]
Her giver det mest mening at bruge f_table_title fra GC2 API'et. Hvis dette ikke er tilgængeligt bruges f_table_name.
