### ISSUE TITLE
Kategori:Teams side mangler

### ISSUE THREAD

**Issue by JosefAssad** [JosefAssad/SeMaWi#32]

**Comment by JosefAssad** [comment]
Lille opgave, kræver ikke mere end 1 time.

**Comment by lenethystrup** [comment]
GO

**Comment by lenethystrup** [comment]
Det sammen gælder vel sagtens grupperne?

**Comment by JosefAssad** [comment]
Ja, men kun fordi at Gruppe klassen ikke er implementeret endnu. :)

**Comment by JosefAssad** [comment]
Kategori:Teams kan godt rumme mere indhold, men den findes i hvert fald nu. Vi vernter til der kommer mere aktivitet på systemet så finder vi ud af hvad siden skal indeholde.
