### ISSUE TITLE
Kun Geodata fra KLE-schemaer

### ISSUE THREAD

**Issue by ballerupgis** [JosefAssad/SeMaWi#36]
Lige nu hentes alle data fra GC2 API'et. Det skal kun være schemaer (f_table_schema) med præfix _XX_ som skal indhentes i SeMaWi (_00_grundkort skal som det eneste ikke hentes ind). 

d.d. er det skemaerne herunder, men der vil blive oprettet flere med tiden: 
"_01_fysisk_plan_og_naturbeskyt"
"_03_boliger"
"_04_parker_fritids_idraetsanlaeg_landskabspleje"
"_05_veje_trafik"
"_06_spildevand_vandloeb"
"_09_miljoebeskyttelse"
"_13_forsyning"
"_14_beredskab"
"_17_undervisning"
"_19_kulturhistoriske_institutioner"
"_20_kulturvirksomhed"
"_21_biblioteker"
"_24_erhvervsforhold"
"_27_social_service"
"_28_dagtilbud"
"_29_sundhed"
"_82_kommunens_ejendomme_lokaler"
"_84_offentlige_valg"

**Comment by JosefAssad** [comment]
Det tror jeg kan klares med en lille regexp nogenlunde [her](https://github.com/JosefAssad/SeMaWi/blob/71abfa27934665743fe5d1f173a7d4b7ce260035/gc2/gc2smwdaemon.py#L42).

Regner med at det vil kunne klares på 3 timer inkl. opdatering af cron scriptet på produkton.

**Comment by JosefAssad** [comment]
Er det alene præfiksen `_00_` som indikerer at en tabel skal springes over? Eller er det hele præfiksen `_00_grundkort`?

**Comment by JosefAssad** [comment]
Og, kan i kigge på Geodata oversigten på dev serveren? Det er implementeret der, skal lige høre om det ser rigtigt ud inden jeg pusher til githu  og prod.

**Comment by ClockEnd** [comment]
præfix _01_ osv (altså med et tal), er som udgangspunkt skemaer der medtages, hvis der er data i skemaet. Ellers er det de datasæt som har et KLE-nr tilknyttet som skal med, det er i virkeligheden den mest sikre metoden til udvælgelse af geodata til SeMaWi

**Comment by ClockEnd** [comment]
Tjekker dev, i dag eller mandag

**Comment by baffioso** [comment]
Hvis table_title ikke er tilgængelig skal table_name bruges

**Comment by JosefAssad** [comment]
OK, jeg implementerer 2 ændringer på DEV på lørdag:

Alle tabeller med _00_ (ikke kun præfiks) springes over, og:

Jeg analyserer om vi ender med unikke sidenavne hvis vi bruger table_title og ellers table_name hvis table_title ikke findes; hvis ja så ændrer jeg scriptet, hvis nej så bliver vi på key og jeg melder tilbage om at der alligevel opstod konflikter.

**Comment by baffioso** [comment]
Det er tabeller som ligger i skemaer (f_table_schema), hvor skemanavnet har præfiks _xx_ som skal medtages. Præfiks på f_table_name er ikke interessant.

**Comment by JosefAssad** [comment]
Ser i hvert fald væsentlig bedre ud med title og hvis ikke så name i stedet for key. Jeg undersøgte tabellerne og alle sidenavne er i øjeblikket unikke med den sidenavngivningsregel. Det vil stadig være smart at snakke med Mapcentia for at se om de har kloge ideer for pænere tabelnøgler. Indtil den tid skal i huske at double checke når i retter i tabeller eller tilføjer, at f_table_title med f_table_name som fallback skal være unik.

@baffioso hvis du kigger på dev og giver thumbs up (og lukker denne issue) smider jeg scriptet på prod.

**Comment by baffioso** [comment]
Ser godt ud ved første øjekast. Vi kigger det igennem mandag og vender tilbage

**Comment by ClockEnd** [comment]
Tjek
Den 21/11/2015 18.03 skrev "baffioso" <notifications@github.com>:

**Comment by baffioso** [comment]
Jeg har ikke yderligere kommentarer til Geodata som du må gerne smide det i produktion.
