### ISSUE TITLE
Indsatser: visning af brugere

### ISSUE THREAD

**Issue by JosefAssad** [JosefAssad/SeMaWi#39]
På Indsats oversigten vil det være hensigtsmæssigt at de brugere der er ansvarlige for eller deltager i en Indsats vises nogenlunde sådan her:

![users](https://cloud.githubusercontent.com/assets/1040956/10017395/3405e632-612e-11e5-9a6a-004c0b0e8faf.png)

**Comment by lenethystrup** [comment]
Ja - der skal kunne være flere ansvarlige for samme indsats ( f.eks. i hver sin gruppe) men det skal KUN være initialerne "ltk" der vises

**Comment by lenethystrup** [comment]
spørgsmålet er om det skal hedde "brugere" - men istedet "person" eller "medarbejder" - der jo så kan agere som både bruger, deltager, ansvarlig, og så videre. Måske vi lige skal se på det ifht rammearkitekturen sammen

**Comment by JosefAssad** [comment]
Enig. Når vi tager fat i denne issue tror jeg det vil være godt at det sker i sammenhæng med f.eks. eventuel opkobling til autoritativ organisationskilde (AD eller på sigt OS2Mo), og at vi har Marius med undervejs.

**Comment by lenethystrup** [comment]
Ja - lige præcis!

**Comment by JosefAssad** [comment]
Mener denne issue kan lukkes. Enig?

**Comment by lenethystrup** [comment]
enig
