### ISSUE TITLE
Semantic Maps

### ISSUE THREAD

**Issue by ClockEnd** [JosefAssad/SeMaWi#47]
Vi skal have kigget på Semantic Maps, i begyndelsen af 2016

**Comment by JosefAssad** [comment]
Semantic Maps version 3.4 er udgivet i dag. Værd at nævne er, at det bliver den sidste version af Semantic Maps da funktionaliteten flyttes ind i den mere generelle Mediawiki udvidelse [Maps](https://www.mediawiki.org/wiki/Extension:Maps).

Det giver os noget konkret vi kan bruge til at planlægge udrulning af denne udvidelse, nemlig at vi inkluderer Maps i stedet for.
