### ISSUE TITLE
Niveauer i organisation

### ISSUE THREAD

**Issue by ClockEnd** [JosefAssad/SeMaWi#48]
Hvilken underinddeling passer bedst ift lederansvar?

**Comment by ClockEnd** [comment]
Vi skal kun lave et absolut minimum, vi venter på OS2MO

**Comment by JosefAssad** [comment]
I øjeblikket har vi en flad model for organisation i SeMaWi. Det vil sige, en klasse OrganisatoriskEnhed og en klasse under som hedder Team.

Som @ClockEnd siger så skal vi begrænse det implementerede så vidt som muligt for at undgå midlretidige investeringer som bliver "smidt væk" når enten OS2MO er på banen, eller hvis organisation kan indlæses/hentes fra AD.

Mit forslag er, at vi gør følgende:

1. Luk denne issue og peg på issue #49 
2. På issue #49 laver vi issue'n om så den mere generelt omhandler at læse organisation og brugere fra en ekstern autoritativ kilde

Giver det mening?

**Comment by ClockEnd** [comment]
se issue #49
