### ISSUE TITLE
klasse til tværgående grupper

### ISSUE THREAD

**Issue by JosefAssad** [JosefAssad/SeMaWi#51]
Der skal implementeres en ny klasse Gruppe der ligner Team men ikke er tilknyttet en OrganisatoriskEnhed. Det er for at gøre det muligt at oprette tværgående grupper til forskellige formål med relation til øvrige elementer i SeMaWi datamodellen.

Efterfølgende skal det være muligt at knytte en Gruppe til en Indsats.

**Comment by lenethystrup** [comment]
Hvis i.kke det generer nogen vil jeg foretrække betegnelsen "Gruppe" - det signalerer en bred forståelse, og kan anvendes frit

**Comment by JosefAssad** [comment]
Er meget enig. Hvis det senere viser sig at betegnelsen er for bred kan vi jo bare omdøbe de relevante wikisider (properties, template, form). :)
