### ISSUE TITLE
GC2 import skal ikke overskrive Fritekst

### ISSUE THREAD

**Issue by JosefAssad** [JosefAssad/SeMaWi#62]

**Comment by JosefAssad** [comment]
Mere generelt er der behov for, at tage højde for allerede indtastet data. For eksempel har datamodellen i wiki'en en tabelejer; det findes ikke i GC2's json. Det felt bliver i øjeblikket overskrevet.

I bund og grund er det logiske her at videreudvikle integrationen så den er tovejs i stedet for envejs import.

Cc @baffioso

**Comment by baffioso** [comment]
Vi snakker med Martin fra Mapcentia om mulighederne for at importere fra semawi

**Comment by baffioso** [comment]
Det det begynder at blive mere og mere aktuelt at indtaste oplysninger om geodata. Er det afhængigt af https://github.com/mapcentia/geocloud2/issues/26 ?

**Comment by JosefAssad** [comment]
Ikke umiddelbart afhængig, nej. Den issue to henviser til er en byggeklods vi kan bruge til blandt andet at skifte fra batch import til online data sync fra GC2 til SeMaWi (se issue #27 ). Og gøre koblingen mellem SeMaWi og GC2 mere løs, hvilket er en rigtig stor fordel når vi tager i betragtning at der er en del flere systemer der også på sigt får gavn ud af, at kunne snakke med GC2.

Jeg tror vi kan løse denne ved at modificere scriptet `gc2smwdaemon.py` så det hender side Geodata_X fra GC2, henter samme fra SMW, og kun erstatter template kaldet i det hentede fra SeMaWi og skriver det tilbage.

Det har dog en stor betingelse, og det er at de unikke nøgler for tabeller ikke ændres. For hvis den bliver øndret så matcher de to sider ikke og så kan scriptet ikke matche tabel i GC2 og wikiside i seMaWi for at bevare fritekst feltet.

I praksis betyder det at vi skal tage løsningen på #36 ([de her](https://github.com/JosefAssad/SeMaWi/blob/4a468b3e8b1bd93c39e6d9bd3e7bad173d26b306/gc2/gc2smwdaemon.py#L146) kodelinjer)i betragtning. Det sidenavn som repræsenterer en geodata tabel må ikke ændres, ellers vil scriptet ikke kunne matche tabeller med sider og derved bevare wiki friteksten.

En pænere løsning vil være at finde noget andet som unikt identificerer tabeller i begge systemer og som ikke bliver ændret, sandsynligvis kombination af skemanavn og tabelnavn og bruge det til at matche sider med tabeller, men det kan kræve lidt ekstra programmeringstid.

Kan i fortælle lidt om hvis/hvornår følgende felter ændres i GC2?

1. tabelnavn
2. tabelskema
3. key

**Comment by baffioso** [comment]
1. Tabelnavnet bliver ændret hvis vi finder ud af, at navnet ikke passer godt til tabellens indhold. Dette sker meget sjældent, men vi ske en gang i mellem. Vi har de 2 øverste hierarkier af KLE som præfiks og hvis vi finder ud af at tabellen hører til et anden KLE-emne kan navnet blive ændret. Jeg er dog kommet lidt i tvivl om vi fortsat skal have KLE som præfiks på tabeller, da vi har alle tre KLE niveaur stående i GC2.

2. Skemanavne har vi aldring ændret i, med da de også har KLE-præfiks vil det kunne ske, når der sker ændringer i KLE. 

3. Key er en kombination af skema og tabelnavn samt navnet på tabellens geometrikolonnen (the_geom). Dette skulle være en unik nøgle, men bliver selvfølgelig ændret, hvis der sker ændringer i tabel eller skemanavn (punkt 1 og 2).

Giver det mening?

**Comment by ClockEnd** [comment]
Det giver god mening
Den 08/01/2016 12.54 skrev "baffioso" <notifications@github.com>:

**Comment by JosefAssad** [comment]
Jeps, rigtig god forklaring. Lige før det skulle skrives på wikisiden for GC2. :)

Det betyder i praksis at alle 3 datafelter kan ændres hvilket gør det udfordrende at garantere at der kan matches en tabel fra GC2 med en side i SeMaWi.

En ting som kan hjælpe er, hvis der introduceres et felt i GC2 som er unikt og uforanderlig. For eksempel bruger LoRA systemet som @mariushart har i FK GUID'er. Det vil dog kræve indsats fra Mapcentia og er ikke en lige her og nu løsning.

En anden mulighed er mer workaround-agtig (og dermed mindre optimal) men hurtigere. Muligheden er: vi tilføjer en macro i Template:Geodata som lister de undersider en Geodata side har, og så skriver i undersider til Geodata tabeller i stedet for direkte i Fritekst feltet. På den måde vil siderne ikke overskrives, men hvis matching nøglen melem GC2 og SeMaWi ændres så må i huske at gå ind i SeMaWi og "flytte" undersiderne så de peger på den nye side der er oprettet til tabellen efter at sidetitlen har ændret sig som følge af ændret key/skema/tabelnavn.

Jeg foreslår vi gør begge dele, hore med Mapcentia og kigge på undersider som midlertifig løsning.

**Comment by mapcentia** [comment]
Key feltet er en unik nøgle, men kan ændres da navnene på både schema, tabel og geom felt kan ændres. Fx ændres schemanavn, hvis tabellen flyttes til et andet schema. Jeg ser ikke det store i at tilføje et GUID felt i GC2's metadata tabel.

**Comment by baffioso** [comment]
Det lyder godt. Vi giver @mapcentia grønt lys til lavet et GUID på metadata.

**Comment by JosefAssad** [comment]
@mariushart noget særligt at være opmærksom på, hvis GC2 GUID'er skal læses i eller fra LoRA?

**Comment by mapcentia** [comment]
Så er der GUID på datasæt i GC2 Meta. Egenskaben hedder UUID (som det hedder i PostGreSQL verdenen). De er genereret med PostGreSQL funktionen "uuid_generate_v4"

**Comment by JosefAssad** [comment]
Brilliant!

@mapcentia Nu spørger jeg dumt, der hvor vores sync læser tabel metadata fra, er urler som `http://$CLIENT.mapcentia.com/api/v1/metadata/$CLIENT/` . I det returnerede JSON på den URL, er det der GUID feltet vil dukke op?

**Comment by mapcentia** [comment]
@JosefAssad Ja, det er det. Det er dog ikke rullet ud på *.mapcentia.com serveren endnu, da den bliver sync'et fra den interne, hvor GUID'erne er skabt.

**Comment by JosefAssad** [comment]
![uuid](https://cloud.githubusercontent.com/assets/1040956/12446609/498029c8-bf6b-11e5-8256-b5524e88912c.png)

Lovely, tak!

**Comment by baffioso** [comment]
Det er stærk tobak! 
@JosefAssad kan du sige noget om hvornår du kan have noget klar?

**Comment by JosefAssad** [comment]
Planen er at have noget til test i uge 5. Skal nok give lyd.

**Comment by baffioso** [comment]
Det lyder godt.  Vi ses mandag

**Comment by JosefAssad** [comment]
@baffioso @ClockEnd test på dev venligst.

Blandt det i skal teste:

1. Kig i den udvidede datamodel med GUID
2. skriv noget i et fritekst felt og check at det bliver bevaret korrekt
3. check hvis en tabel slettes i GC2 at den også slettes fra SeMaWi
4. Check at en nyoprettet tabel i GC2 ligeledes oprettes i SeMaWi

I øjeblikket kører scriptet en gang i timen:

`0       5       *       *       *       echo 'source /home/josef/.virtualenvs/gc2smw/bin/activate; python /home/josef/.virtualenvs/gc2smw/gc2cronjob/gc2smwdaemon.py' | /bin/bash`

**Comment by baffioso** [comment]
Har kigget på http://dev.notanumber.dk/ og skrevet fritekst ind på http://dev.notanumber.dk/index.php/Geodata_06_00_regnopland_befaestelse som ikke er blevet overskrevet - Optur.
Har oprettet en ny tabel i GC2 http://ballerup.mapcentia.com/api/v1/metadata/ballerup/_03_boliger som har `f_table_title: "Tester SemaWu" `, men den er ikke slået igennem i wikien.

**Comment by JosefAssad** [comment]
Den testtabel du har oprettet, den er nu slettet? Jeg spørger, fordi scriptet læser fra http://ballerup.mapcentia.com/api/v1/metadata/ballerup/ så jeg ville starte med at gå ind der og spore hvor det er det sker at siden ikke bliver oprettet.

**Comment by baffioso** [comment]
Så er der oprettet tabel `test ` i schemaet `_03_boliger`

http://ballerup.mapcentia.com/api/v1/metadata/ballerup/_03_boliger

Sørger for den ikke bliver fjernet i nat.

**Comment by JosefAssad** [comment]
Hm, jeg kan godt se den her:

![testpage](https://cloud.githubusercontent.com/assets/1040956/12715546/3150ba10-c8db-11e5-8db1-29d1badc200c.png)

http://dev.notanumber.dk/index.php/Geodata_Test_SeMaWi

Skal vi prøve at double checke? Scriptet kører i cron hver time ved 0 minutter og kan tage op til 5-10 minutter. Så en test kan være som følgende:

1. tid XX:15: fjern testtabellen
2. tid XX+1:15: verificer at den tilsvarende wikiside ikke findes
3. tid XX+1:15: tilføj testtabellen i GC2
4. tid XX+2:15: verificer at den tilsvarende wikiside findes

Hvordan lyder det?

**Comment by baffioso** [comment]
Jeg har nu slettet `test` tabellen og oprettet en ny `test_2` tabel i GC2 og venter spændt til 18:15. Så håber vi http://dev.notanumber.dk/index.php/Geodata_Test_SeMaWi er død og 
http://dev.notanumber.dk/index.php/Geodata_Test_SeMaWi_2 lever

**Comment by baffioso** [comment]
@JosefAssad virker ikke til mine ændringer er slået igennem.

**Comment by JosefAssad** [comment]
Har lige testet. Scriptet virker, den nye tabel erstatter den gamle.

Skal stadig fixe cronjobbet men det er operations og ikke kode så der behøves ikke mere kodemæssigt her.

Når jeg finder ud af hvorfor cron brokker sig ruller jeg scriptet ud på prod.

**Comment by baffioso** [comment]
Fedt.

**Comment by JosefAssad** [comment]
![gc2works](https://cloud.githubusercontent.com/assets/1040956/12725246/0722249a-c912-11e5-92a6-43b615d44421.png)

**Comment by baffioso** [comment]
Tjek. Havde du ikke `X X * * *` som tid? Hvis det skal køre en gang i timen, skal det vel være `X * * * *`

**Comment by JosefAssad** [comment]
ops talk = IRC :)

**Comment by baffioso** [comment]
Netop, jeg smutter ud og laver noget aften mad til familien. LOL

**Comment by baffioso** [comment]
Fritekst indeholder tekst

![image](https://cloud.githubusercontent.com/assets/7534153/12751240/4429ff5c-c9bc-11e5-9ebb-8ca1b7ea1af7.png)

**Comment by JosefAssad** [comment]
Yep skulle fungere nu. Scriptet kører kl 0500 på PROD.

I må alligevel gerne teste en sidste gang inden i lægger kritisk indhold op.

Vigtig ting at huske: sletter i en tabel fra GC2 bliver siden også slettet fra SeMaWi, inklusiv fritekst.

**Comment by baffioso** [comment]
Kan se [test-tabellen](http://semawi.notanumber.dk/index.php/Geodata_SeMaWi_Test_Produktion) jeg oprettede i produktionsdatabasen er kommet med, så det er godt. Der er dog stadig se der stadig er lidt skabelonrester i fritekstfeltet.
![image](https://cloud.githubusercontent.com/assets/7534153/12775755/c06ffcd0-ca50-11e5-87cc-c8be4a873de0.png)

**Comment by JosefAssad** [comment]
Mener denne er løst nu.
