### ISSUE TITLE
Skal gratis systemer til bl.a. datavedligehold med?

### ISSUE THREAD

**Issue by baffioso** [JosefAssad/SeMaWi#64]
Vi bruger bl.a. Miljøportalen til at vedligeholde data. Skal de med i Wikien?

**Comment by ClockEnd** [comment]
Hvis systemerne har en dataopgave tilknyttet, så ja syn's jeg

**Comment by ClockEnd** [comment]
Miljøportalen skal nedbrydes i sub-systemer der passer til KLE?

**Comment by JosefAssad** [comment]
Som jeg ser det så er et system del af jeres portefølje hvis det har funktioner eller data som i anvender. Det er ret bredt, men det er sådan jeg ser en portefølje. :) På den (lidt) længere bane vil jeg gerne modellere integrationerne mellem systemerne i porteføljen, for der kommer der nogle cool use cases. Så bare fordi et system ikke medfører licensomkostninger er ikke en grund til ikke at medtage den. Faktisk kan eksterne systemer i ingen eksplicitte aftaler på muligvis også påvirke jeres portefølje.

Kontrakter/aftaler på systemer er et andet meget væsentligt modelleringsaspekt der er meget nært mit hjerte. En aftale medfører forpligtelser, licensomkostninger er et instans af sådan en forpligtelse. Et andet eksempel er ophavsret, og copyleft er et tredje. Alle disse er eksempler på metadata der er ret relevant for jeres systemportefølje. Så det ville være smart at modellere netop det. Ideelt i samarbejde med nogle indkøbsfolk eller lignende med interesse for it og vilje til at eksperimentere.

Måske vil det være godt med en ændring i System klassen så der kan defineres subsystemer? I eksemplet med Miljøportalen er det nok de systemer som PULS, NDB, DKJord osv i tænker på, er det rigtigt?

Jeg foreslår vi deler denne issue op i tre og lukker den:

1. Systemaftaler (fx. gratis systemer)
2. Subsystemer
3. Klasser for data

Hvad siger i?

**Comment by lenethystrup** [comment]
god ide - jeg har også tanker om at bruge subsystemer ifbm strategiske indsatser
