### ISSUE TITLE
Kompetencer på brugere

### ISSUE THREAD

**Issue by MadsBorggaard** [JosefAssad/SeMaWi#66]
Kan man gøre så man kan lave et felt på brugere i stil med afhængigheder, men bare bruge det til kompetancer, man skal også kunne søge i det.

F.eks. - GIS, GeoData, Database, Python

**Comment by ClockEnd** [comment]
@MadsBorggaard god ide, i sammenhæng med organisationskomponenten vil det give god mening

**Comment by JosefAssad** [comment]
Ja, det ville være RIGTIG spændende at begynde at modellere og registrere kompetencer. Det er dog et funktionelt område som giver mere jo flere der er der bruger systemet.

Der er meget smarte eksempler på use cases, for eksempel at sammenligne et organisatorisk områdes aggregerede kompetencer med kompetencer der registreres ifm. Indsatser, eller rapporter som danner overblik over kompetenceforskelle mellem det et system kræver og de kompetencer systemadministratoren har (så spotter vi fx. folk der muligvis vil noget mere end det de gør i dag!) osv.

Ideelt vil en datamodel for kompetencer designes sammen med HR folk. :)

**Comment by JosefAssad** [comment]
Se også issue #57. Da de handler om mere eller mindre det samme lukker jeg denne issue så vi ikke har duplicates. :)
