### ISSUE TITLE
Typer personfølsom information kan være mere nuanceret

### ISSUE THREAD

**Issue by JosefAssad** [JosefAssad/SeMaWi#67]
@mariushart kommer med liste.

**Comment by JosefAssad** [comment]
Cc @mariushart ping :)

**Comment by mariushart** [comment]
Persondataloven opdeler personoplysninger i tre typer:

1. Følsomme oplysninger
2. Oplysninger om andre rent private forhold
3. Almindelige ikke-følsomme oplysninger

**Comment by JosefAssad** [comment]
@ClockEnd @baffioso ok med de typer @mariushart indikerer her?

![personfolsomminfo-67](https://cloud.githubusercontent.com/assets/1040956/12975838/6a10ff9a-d0bf-11e5-98c5-281b0c66e191.png)

**Comment by JosefAssad** [comment]
Det handler her om Property:SystemPersonfølsomType . I BALK er status i øjeblikket:

Property'et har følgende gyldige værdier:

* CPR
* Fødselsdato
* Bankinformation
* Kreditkort

Der er 4 systemer der anvender property'et med værdier "CPR" og "Fødselsdato". Det betyder, at hvis vi skifter til Marius' forslag så skal den info laves om.

Skal vi det? Er de eksisterende værdier anvendt og nødvendige og blokerer for, at vi ændrer de gyldige værdier for det property?

**Comment by JosefAssad** [comment]
Done.
