### ISSUE TITLE
Oversigten over indsatser skal forenkles

### ISSUE THREAD

**Issue by lenethystrup** [JosefAssad/SeMaWi#73]
sidste kolonne på denne side http://semawi.notanumber.dk/index.php/Kategori:Indsatser - skal kun hedde "Fremdrift"

**Comment by lenethystrup** [comment]
I kolonnen "Hvem" skal vises såvel - ansvarlig med fed - som deltagende gruppe - og brugere - ligesom for teams

**Comment by JosefAssad** [comment]
Tror denne kan lukkes nu?
