### ISSUE TITLE
Upload flere forskellige filtyper

### ISSUE THREAD

**Issue by baffioso** [JosefAssad/SeMaWi#75]
Ligenu er vi begrænset til kun at kunne uploade følgende filtyper

![image](https://cloud.githubusercontent.com/assets/7534153/11739396/6ef9cd3e-9feb-11e5-81fa-98adf5491368.png)

Er det muligt at få lov til at uploade .pdf, .doc, .xls, .odt m.m.

**Comment by JosefAssad** [comment]
Done.

**Comment by baffioso** [comment]
Takker
