### ISSUE TITLE
Anvend OS2KLE søgeord

### ISSUE THREAD

**Issue by JosefAssad** [JosefAssad/SeMaWi#76]
Stor json fil med relevante søgeord findes her:

http://www.taxon.dk/da/taxonomier

Og i øvrigt kan det være rigtig smart at feede nye søgeord tilbage til Taxon/OS2KLE fra SeMaWi.

**Comment by ClockEnd** [comment]
Som en form for crowdsourcing, eller med noget governance på?

**Comment by JosefAssad** [comment]
Det tror jeg er noget vi selv kan bestemme, afhængig af hvor det bliver implementeret.

Rent teoretisk: hvis fx vores implementation har mulighed for manuel keyword opslag i stedet for automatisk opslag så kunne vi logge opslag og identificere de mest hyppige opslag med nul resultater, og mappe dem til KLE emnenumre. De mappings kunne muligvis være interessante for OS2KLE og Taxon. :)

Meget afhænger af, hvordan det implementeres.

**Comment by ClockEnd** [comment]
Interessant

**Comment by JosefAssad** [comment]
Jeg vil gerne lave en lille prototype i 2 med OS2KLE søgetermer i SMW subobjects på KLE siderne. Egentlig implementering kan evt. komme efter hvis prototypen fungerer.

Årsagen til, at jeg vil prøve dette approach er at der er rigtig mange søgetermer, og det vil give RIGTIG mange flere MW sider hvis de implementeres som egentlige sider.

**Comment by ClockEnd** [comment]
Vi har i den grad brug for søgeordene på geodatasiderne

**Comment by JosefAssad** [comment]
Alright, jeg bruger denne kommende mandag på at finde et løsningsforslag.

**Comment by ClockEnd** [comment]
Glimrende

**Comment by JosefAssad** [comment]
Jeg blev lige grebet af denne issue og kiggede lidt på den. En designmæssig overvejelse her:

Som jeg forstår det så skal man kunne indtaste et stikord i et søgefelt og derved komme frem  til geodata tabeller. Men der er et spørgsmål om man skal komme direkte til geodata tabeller, eller om man skal få en KLE emne oversigt og derfra komme til geodata tabeller.

Jeg spørger, fordi jeg tænker på en måske lidt uforventet løsning her.

Den løsning er, at man søger på et stikord og kommer frem til wikisiden for det relevante KLE Emne. Men så på den side er der en automatisk genereret oversigt over hvilke geodata tabeller er tagget med det KLE emne. Og DERFRA kan man klikke sig ind i de pågældende geodatasider.

Den løsning åbner designmæssigt for, at man i fremtiden kan samle på en KLE side oversigten over fagligt indhold som er tagget med det emne uanset vertikal; om det er geodata sider eller sider der dokumenterer f. eks. processer.

Jeg er ikke 100% sikker endnu men min mavefornemmelse siger mig at det også er en anelse nemmere at implementere (altid en fordel :) )

**Comment by ClockEnd** [comment]
Det er bestemt en god ide. Jeg tror, at folk først og fremmest skriver almindelige søgeord som filter1 og derefter klikker sig frem til det ønskede emne. Så der tror jeg din tilgang er korrekt. Noget andet vi godt ville have ud af KLE på Geodata, var at sende dem med ud på OpenDataDK, altså sammen med GeoJson og de andre metadata fra GC2 og SeMaWi. Det vil være en kæmpegevinst i forhold til datasammenhæng og løst koblede metadata

**Comment by JosefAssad** [comment]
Et praktisk eksempel. Antag at et gyldigt stikord på KLE emne 00.14.12 er "Test1".

Hvis du kigger på forsiden på DEV serveren så er der en ny kasse til stikordsopslag. Indtast "Test1" og klik på "Run Query", og så videre til det emne du får som søgeresultat. Den linker til KLE emnet, og på KLE emnets side vises hvilke Geodata tabeller der er.

Feedback?

**Comment by ClockEnd** [comment]
Exactly :-)

**Comment by JosefAssad** [comment]
Betyder det du har du testet? :)

**Comment by ClockEnd** [comment]
Ja

**Comment by JosefAssad** [comment]
OK så implementerer jeg den model på mandag. Bare for dokumentationens skyld består implementation af følgende trin:

1. Make one page with subobjects mapping all the stikord to emne numbers [0]
2. In the Template:Emne add via an ask query a list of all geodata tables for that emne
3. Make a Template:KLEStikordOpslag with an ask query
4. Make a form to query this template
5. Use the [embed query form syntax](https://www.mediawiki.org/wiki/Extension:Semantic_Forms/Creating_query_forms#Embedding_query_forms) to put a search box in a masonry block on the front page


[0] Den her er den komplekse. Jeg vil skrive et python script som konverterer Taxon's json data til Semantic MediaWiki subobjects. Planen er at smide dem alle sammen på en side, men der skal undersøges om det har performance konsekvenser. Der er jo RIGTIG mange.

**Comment by ClockEnd** [comment]
Præcis. Og subobjects hindrer ikke at KLEnumrene kan videreeksporteres?

**Comment by JosefAssad** [comment]
Well hvis det er for opendata.dk's skyld så tror jeg ikke rigtig vi behøver hente KLE numre fra SeMaWi. Eksport af geodata til opendata.dk foregår via GC2, og GC2 har allerede KLE numre i skema'et, så den eksport funktion der kan bare hente det direkte fra GC2.

Make sense?

**Comment by ClockEnd** [comment]
Tror vi skal tegne det, under indtagelse af øl :-)

**Comment by JosefAssad** [comment]
Den kasse på DEV forsiden til søgning i stikord, gider du prøve den igen? OS2KLE stikord burde fungere nu men lad os kalde det "pre-alpha" :)

**Comment by JosefAssad** [comment]
Er vi klar til at flytte denne funktion til produktion? Med samme søgekasse på forsiden?

**Comment by baffioso** [comment]
Jeg siger go

**Comment by JosefAssad** [comment]
Er implementeret.
