### ISSUE TITLE
Bruger - Geodataejerskab - konfiguration

### ISSUE THREAD

**Issue by mariushart** [JosefAssad/SeMaWi#80]
Der er behov for en konfigurationsmulighed, så systemet let kan tilpasses forskellige organisationer.
Fx. skal det kunne konfigureres at hvis en bruger ikke har et Geodataejerskab skal feltet 'Geodataejerskab' ikke vises.

**Comment by JosefAssad** [comment]
Ja, overvejer lidt hvordan vi griber denne an.

En potentiel løsning som skalerer rimelig godt:

1. Opret en konfigurationsside der erklærer lokale variabler som (pseudocode) `GEODATA_ON_USERPAGE=True/False`
2. Wrap geodataoversigten i en `#ifeq`
