### ISSUE TITLE
System exception

### ISSUE THREAD

**Issue by mariushart** [JosefAssad/SeMaWi#81]
Hvis man opretter afhængigheder i fritekst i.e systemer som ikke findes i forvejen opstår der exception ved submit.

Parser ved 1 afhængighed der ikke findes
Exception ved 2 afhængigheder

**Comment by mariushart** [comment]
Muligvis Category afhængighed - fejl ved manglende

**Comment by JosefAssad** [comment]
Fixed temporarily with [this patch](https://phabricator.wikimedia.org/T68202#697806).

Permanent fix comes via upcoming MW 1.26 upgrade which brings in a SemanticForms parser call update.

**Comment by JosefAssad** [comment]
Scratch that, patch introduced regressions so I upgraded SemanticForms to REL1_25.
