### ISSUE TITLE
skift til docker

### ISSUE THREAD

**Issue by JosefAssad** [JosefAssad/SeMaWi#91]
Gør det nemmere at teste, deployere, og synkronisere versioner på tværs af brugere.

Olplagt at opgradering til MW 1.26 kommmer med denne issue.

**Comment by JosefAssad** [comment]
NB dette vil med høj sandsynlighed medføre opgradering af MW og extensions; det er en god ting, men skal planlægges og testes meget nøje.

**Comment by baffioso** [comment]
Giver måske også mening ifht. at implementere på intern applikationsserver, hvor vi blandt andet har GC2  kørende.

**Comment by JosefAssad** [comment]
Ja det er også oplagt. Jeres GC2 produktionsinstans, det er en kørende docker container?

**Comment by baffioso** [comment]
Så vidt jeg ved er det ikke i container på den nuværende server, men kan være det kommer på den nye. Ved at @mapcentia har det klar

**Comment by JosefAssad** [comment]
Som del af migration til Docker skal vi kunne eksportere "SeMaWi" som datamodel i en samlet XML fil. Det er det der er formålet med kategoriet "SeMaWi", at udvælge til eksport de sider der sammmen udgør "SeMaWi" produktet.

Der løber vi ind i en begrænsning i MediaWiki da funktionen som lister sidetitler i et kategori under specielsiden Special:Export har en (ikke så godt dokumenteret) øvre grænse på 5000 sidetitler.

Vi har væsentlig flere end 5000 sider i SeMaWi produktet, med bl.a. KLE2 og - i fremtiden - øvrige funktioner som systemtaksonomier osv.

Jeg har skrevet en patch til MediaWiki core som nu venter på review for at merges i MediaWiki 1.27 som er en Long Term support udgave og udkommer i April. Det er efter release af SeMaWi 2016_01, så indtil den tid patcher vi manuelt i MediaWiki 1.26 serien (som er hvad vi forventer SeMAWi 2016_01 vil basere sig på).

Link til patchset i WikiMedias gerrit: https://gerrit.wikimedia.org/r/267038

**Comment by mapcentia** [comment]
Docker er nu installeret på serveren.

**Comment by baffioso** [comment]
lækkert

**Comment by JosefAssad** [comment]
Vi har nu et brugbart Docker setup, og dockerfile og tilknyttet build context er nu merged i `master`.

Drifsmæssige tiltag håndteres off-github (dialog her vedrører kun kodeændringer).
