### ISSUE TITLE
indledende implementation af "kontoplan-lite"

### ISSUE THREAD

**Issue by JosefAssad** [JosefAssad/SeMaWi#93]
Som metadata til kontrakter mangler vi en datamodel for økonommiske konti.

Vi starter med en 0.1 som baserer sig på 5 niveauer som anvendes til kontraktstyring i FK.

**Comment by JosefAssad** [comment]
Cc @mariushart @lenethystrup @baffioso @ClockEnd

**Comment by JosefAssad** [comment]
@mariushart vi fokuserer i øjeblikket på it kontraktstyring. Skal vi tage denne i milestone 2016_02?

**Comment by JosefAssad** [comment]
2016_01 kommmer med kontoplan-lite funktionalitet som del af en ny klasse til registrering af it kontrakter. Den vil bestå af 2 kontoplan niveauer og er modelleret efter et internt Microsoft Access værktøj i Frederiksberg Kommune.

Relaterede opgaver er:

1. @mariushart og undertegnede præsenterer funktionen over for BALK
2. Samlet community vurdering af funktionerne i 2016_02 milestonen mhp. at inddrage feedback fra øvrige brugeres kontraktansvarlige og sikre at funktionen tjener alle SeMaWi brugere, evt. med videreudvikling.

**Comment by JosefAssad** [comment]
Sneak preview: https://www.youtube.com/watch?v=sJCwguBPprY

Cc @mariushart @baffioso @ClockEnd

**Comment by mariushart** [comment]
Amazing!
Det fungerer meget fint.
Videoen var.... skræmmende :D

**Comment by JosefAssad** [comment]
Jeg mener foreløbigt vi kan lukke denne issue. Jeg fornemmer vi kommer til at udvide kontoplan funktionalitet i fremtiden, men vi har aftalt at holde os til den "lite" version repræsenteret i de to støttetabeller `TBL_KontoplanNiveau1` og `TBL_KontoplanNiveau2` i Henriks databasemodel.
