### ISSUE TITLE
ny udvidelse: Semantic spreadsheets

### ISSUE THREAD

**Issue by JosefAssad** [JosefAssad/SeMaWi#96]
BALK finansierer udviling af en ny Semantic MediaWiki udvidelse som udstiller properties og sider i et webbaseret regneark. Denne udvidelse vil formentlig udgives i første version i Q1 2016, og den er rigtig spændende.

**Comment by mariushart** [comment]
:+1:

**Comment by JosefAssad** [comment]
Seneste udmelding fra Yaron Koren er, at det kommer med næste version af Semantic Forms, slutning Q1 start Q2 er mit bedste gæt.

**Comment by JosefAssad** [comment]
Funktionen findes nu i git's master branch og flyttes derfor tilbage til 2016_01

**Comment by JosefAssad** [comment]
Lukkes med denne commit: https://github.com/JosefAssad/SeMaWi/commit/ba80368b75154f549cb203f9c4663beeb4cd2798
