### ISSUE TITLE
online bidiectional Kitos integration

### ISSUE THREAD

**Issue by JosefAssad** [JosefAssad/SeMaWi#97]

**Comment by mariushart** [comment]
Alt efter udfald af udbuddet på KITOS, kan der også blive tale om objekt udveksling ie. pyLoRA relation.

**Comment by JosefAssad** [comment]
Passer KITOS udbuddet tidsmæssigt med at denne issue ligger i milestone 2016_02 dvs. Q2 2016?

**Comment by JosefAssad** [comment]
Cc @ClockEnd @baffioso

**Comment by mariushart** [comment]
Som jeg husker det sigtes der til ny aftale med effekt fra 01. april, men med udvikling af fase 2 i løbet af sommeren. Så det er desværre nok først Q3.

**Comment by JosefAssad** [comment]
Alright så skifter vi milestone.

**Comment by JosefAssad** [comment]
Se #215
